### PR TITLE
Convert to using prometheus appendable

### LINKED ISSUE #2037: Flow: use Prometheus directly instead of abstraction
Our Prometheus components (`metrics.scrape`, `metrics.mutate`, `metrics.remote_write`) should behave exactly as Prometheus does. 

Currently, Flow uses an abstraction for its metrics pipeline:

* A [`metrics.Receiver`](https://github.com/grafana/agent/blob/8335534a0efcd4b3115a35b225e82f25dc4100ff/component/metrics/receiver.go#L11) receives samples at a given timestamp
* A [`metrics.FlowMetric`](https://github.com/grafana/agent/blob/8335534a0efcd4b3115a35b225e82f25dc4100ff/component/metrics/receiver.go#L17-L22) represents an individual sample

This abstraction is insufficient in its current state:

* It does yet not support writing exemplars  
* It will not immediately support the upcoming work to write metadata to the WAL 
* It will not immediately support the upcoming sparse histogram work  

It also has behavioral differences:

* #2035 notes that failing to append metrics don't fail the scrape, which may cause `up != 1` alerts to no longer fire. 

The list of behavioral differences may or may not be complete: abstractions introduce uncertainty, where it is harder to know if there is any other documented or undocumented behaviors of the underlying code which the abstraction does not satisfy. 

For all of the issues above to be resolved, the abstraction would have to be changed to become Prometheus-like. Instead of maintaining an abstraction over time to match the behavior of a moving target, it would be easier to remove the abstraction and use Prometheus code directly. 

Good abstractions are hard to make, and should only be attempted after accumulating a ton of experience with all the things it is abstracting over. I would recommend we write components to use their native APIs instead of trying to introduce abstractions. This means that Prometheus components should use Prometheus code, and OpenTelemetry Collector components should use OpenTelemetry Collector code. 

If components use their native APIs, then a shim is needed to move between APIs. This is similar to an abstraction, but it reduces the surface area of where bugs can be introduced, allowing the native code path to always work fully as intended. How these shims would be exposed to users is out of scope of this proposal.

### PR DESCRIPTION
**Pull request by mattdurham**
#### PR Description

This switches over to using the storage.appendable/appender interfaces. Exemplars and metadata aren't supported but the hooks are all there. I didn't want to overload this PR.

#### Which issue(s) this PR fixes
Closes #2037

#### PR Checklist

- [ ] CHANGELOG updated
- [X] Documentation added
- [X] Tests updated

### CODE REVIEW

File: component/prometheus/fanout.go [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+func (a *appender) AppendExemplar(ref storage.SeriesRef, l labels.Labels, e exemplar.Exemplar) (storage.SeriesRef, error) {
+	// TODO implement me
+	panic("implement me")
+}
+
+// UpdateMetadata satisifies the Appender interface.
+func (a *appender) UpdateMetadata(ref storage.SeriesRef, l labels.Labels, m metadata.Metadata) (storage.SeriesRef, error) {
+	// TODO implement me
+	panic("implement me")
+}
```
Comment (rfratto) [inline component/prometheus/fanout.go:132]: Let's remove the panic before merging please, since exemplars definitely get pushed in our deployment env. Returning an error should be safe though.

File: component/prometheus/relabel/relabel_test.go [hunk 2]
```diff
@@ -120,29 +79,30 @@ func TestNil(t *testing.T) {
...
-		Receive: func(timestamp int64, metrics []*prometheus.FlowMetric) {
-		},
-	}
 	l := log.NewSyncLogger(log.NewLogfmtLogger(os.Stderr))
 
-	relabeller, _ := New(component.Options{
+	fanout := prometheus.NewFanout(func(ref storage.SeriesRef, l labels.Labels, tt int64, v float64) (storage.SeriesRef, labels.Labels, int64, float64, error) {
+		if !l.Has("new_label") {
+			panic("must have new label")
+		}
```
Comment (rfratto) [inline component/prometheus/relabel/relabel_test.go:92]: Remove the panic please (also I'm not sure what new_label means)

Comment (rfratto) [reply component/prometheus/relabel/relabel_test.go:92]: Oh, this is in test code, nvm :) 

This would be more idiomatic for our existing tests: 

```go
requires.True(t, l.Has("new_label"), "new_label must be provided") 
```

File: component/prometheus/fanout.go [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+
+type intercept func(ref storage.SeriesRef, l labels.Labels, t int64, v float64) (storage.SeriesRef, labels.Labels, int64, float64, error)
+
+// Fanout supports the default Flow style of appendables since it can go to multiple outputs. It also allows the intercepting of appends.
+type Fanout struct {
+	mut sync.RWMutex
+	// intercept allows one to intercept the series before it fans out to make any changes. If labels.Labels returns nil the series is not propagated.
+	// Intercept shouuld be thread safe and can be called across appenders.
+	intercept func(ref storage.SeriesRef, l labels.Labels, t int64, v float64) (storage.SeriesRef, labels.Labels, int64, float64, error)
+
```
Comment (rfratto) [inline component/prometheus/fanout.go:25]: Have you considered making a separate storage.Appendable interface just for intercept? It would behave similarly to the middleware pattern at that point. As it is now, it feels like Fanout is responsible for a little too much.

File: component/prometheus/fanout.go [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+		children:    make([]storage.Appender, len(f.children)),
+		intercept:   f.intercept,
+		componentID: f.componentID,
+	}
+	for i, x := range f.children {
+		if x == nil {
+			continue
+		}
+		app.children[i] = x.Appender(ctx)
+	}
```
Comment (rfratto) [inline component/prometheus/fanout.go:64]: What about setting the capacity of `children` instead of the length? That way you can remove all the nil checks in the appender itself and guarantee that each child is non-nil.

File: component/prometheus/fanout.go [hunk 5]
```diff
@@ -0,0 +1,131 @@
...
+
+// Append satisfies the Appender interface.
+func (a *appender) Append(ref storage.SeriesRef, l labels.Labels, t int64, v float64) (storage.SeriesRef, error) {
+	if ref == 0 {
+		ref = storage.SeriesRef(GlobalRefMapping.GetOrAddGlobalRefID(l))
+	}
+	nRef := ref
+	nL := l
+	nT := t
+	nV := v
```
Comment (rfratto) [inline component/prometheus/fanout.go:84]: Can we use longer names here please? I personally find that `nL` is harder to read over `l`.

File: component/prometheus/globalrefmap.go [hunk 6]
```diff
@@ -79,6 +79,10 @@ func (g *GlobalRefMap) GetOrAddGlobalRefID(l labels.Labels) uint64 {
 	g.mut.Lock()
 	defer g.mut.Unlock()
 
+	if l == nil {
+		return 0
+	}
```
Comment (rfratto) [inline component/prometheus/globalrefmap.go:84]: Can we add a comment here explaining why we return 0 here? Presumably it's because a nil label set indicates a dropped series, right?

File: component/prometheus/relabel/relabel_test.go [hunk 7]
```diff
@@ -15,100 +17,57 @@ import (
...
+	lbls := labels.FromStrings("__address__", "localhost")
+	relabeller.relabel(0, lbls)
 	require.Len(t, relabeller.cache, 1)
 	_ = relabeller.Update(Arguments{
 		MetricRelabelConfigs: []*flow_relabel.Config{},
 	})
 	require.Len(t, relabeller.cache, 0)
 }
 
-func TestThatValueIsNotReused(t *testing.T) {
```
Comment (rfratto) [inline component/prometheus/relabel/relabel_test.go:57]: Is this test no longer necessary? It felt like a good regression test to have

File: component/prometheus/remotewrite/remote_write.go [hunk 8]
```diff
@@ -71,7 +70,10 @@ func NewComponent(o component.Options, c Arguments) (*Component, error) {
 		remoteStore: remoteStore,
 		storage:     storage.NewFanout(o.Logger, walStorage, remoteStore),
 	}
-	res.receiver = &prometheus.Receiver{Receive: res.Receive}
+	res.receiver = &appendable{
+		inner:       res.storage,
+		componentID: o.ID,
+	}
```
Comment (rfratto) [inline component/prometheus/remotewrite/remote_write.go:76]: If we make the interceptor its own storage.Appendable, then you should be able to replace the custom appendable struct here with the interceptor to reduce some code, I think.

File: component/prometheus/relabel/relabel_test.go (hunk 2 above)
Comment (mattdurham) [reply component/prometheus/relabel/relabel_test.go:92]: Can benchmarks access the testing.T?

Comment (rfratto) [reply component/prometheus/relabel/relabel_test.go:92]: oh, it'd be `b` here then. `require` can be given any `testing.T` or `testing.B` instance

File: component/prometheus/fanout.go (hunk 3 above)
Comment (mattdurham) [reply component/prometheus/fanout.go:25]: I originally did have more specific appendables, but it's really handy to reuse the fanout for tests. There was a fair amount of duplicated code so I refactored to use one that allows some middleware in between.

File: component/prometheus/fanout.go (hunk 4 above)
Comment (mattdurham) [reply component/prometheus/fanout.go:64]: Removed the nil checks from the appender and simplified a bit of the logic. Nils are allowed in the appendable but not the appender.

File: component/prometheus/globalrefmap.go (hunk 6 above)
Comment (mattdurham) [reply component/prometheus/globalrefmap.go:84]: Moreso a guard against bad input and not pollute the cache. The bad input could be a dropped series.

File: component/prometheus/relabel/relabel_test.go (hunk 7 above)
Comment (mattdurham) [reply component/prometheus/relabel/relabel_test.go:57]: With the removal of flowmetric the cache can never be passed the value so it's not necessary. The test was mostly obsolete earlier but now its more explicit that values cannot enter the cache.

File: component/prometheus/remotewrite/remote_write.go (hunk 8 above)
Comment (mattdurham) [reply component/prometheus/remotewrite/remote_write.go:76]: I was torn on this one and did it both ways, and felt that remote_write having its own custom one was warranted because anything interfacing with remote_write will have to do the translation ie appendexemplar and updatemetadata. Where my gut is that other components wont have any customer behavior on those.

File: component/prometheus/relabel/relabel_test.go (hunk 2 above)
Comment (mattdurham) [reply component/prometheus/relabel/relabel_test.go:92]: Doh!

File: component/prometheus/fanout.go (hunk 3 above)
Comment (rfratto) [reply component/prometheus/fanout.go:25]: I'd like a second opinion from @tpaschalis here. My gut feeling is that we shouldn't put both intercept + fanout logic in the same thing, but I don't know if I'm being too idealistic with this.

Comment (tpaschalis) [reply component/prometheus/fanout.go:25]: I think I'd be in favor of a separate appendable here.

If it's only the testing code that gets more complicated by splitting the intercept+fanout logic, then maybe we should give it a try, since we won't be altering the test code that much (it's already tested upstream and we only need to validate our component's behavior).

Comment (mattdurham) [reply component/prometheus/fanout.go]: This is resolved now.

File: component/prometheus/fanout.go [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+	return nil
+}
+
+// Rollback satisifies the Appender interface.
+func (a *appender) Rollback() error {
+	for _, x := range a.children {
+		_, _ = x, a.Rollback()
+	}
+	return nil
+}
```
Comment (rfratto) [inline component/prometheus/fanout.go:91]: Have you considered using a multierror here and returning the error back to the caller so it can make the decision for what to do with error handling?

Ultimately I don't think the fanout should be hiding errors and it should be the callers responsibility.

**Review by rfratto — APPROVED** [review]
LGTM! My only big concern is to change the fanout to _not_ hide errors, since there's a few important things that depend on errors being returned. For example, the target should be marked as failed if it couldn't be written to the WAL (such as having invalid or duplicate labels).
