### PR TITLE
prometheus.operator.*: fix UI issues

### LINKED ISSUE #4512: web interface broken when inspecting prometheus.operator.{{pod,service}monitors,probes} components
### What's wrong?

I configured grafana-agent 0.35.0 with the config below.

~I did not install the `PodMonitor`, `Probe`, `ServiceMonitor` CRDs into the cluster. `grafana-agent` rightfully marks them as unhealthy:~

I port-forward port 80 from the service to my laptop, and see the 3 `prometheus.operator.*` components. So far, so good, so expected.

However, clicking on them breaks the javascript, I get an uncaught type error:

> Uncaught TypeError: Cannot read properties of null (reading 'forEach')

The website is blank, and entirely broken - I can't go back, I need to refresh to get it to work again.

I would expect the website to still work in these cases.

### Steps to reproduce

Point grafana-agent to a cluster with or without the CRDs installed, click on one of the components in the grafana-agent web interface.

### System information

K8s

### Software version

Grafana agent v0.35.0

### Configuration

```text
// Discover PodMonitor resources in all namespaces and scrape the targets they reference.
prometheus.operator.podmonitors "podmonitors" {
  forward_to = [prometheus.remote_write.default.receiver]
}

// Discover Probe resources in all namespaces and scrape the targets they reference.
prometheus.operator.probes "probes" {
  forward_to = [prometheus.remote_write.default.receiver]
}

// Discover ServiceMonitor resources in all namespaces and scrape the targets they reference.
prometheus.operator.servicemonitors "servicemonitors" {
  forward_to = [prometheus.remote_write.default.receiver]
}

// Collect and send metrics to a Prometheus remote_write endpoint.
prometheus.remote_write "default" {
  endpoint {
    url = "http://localhost:9009/api/prom/push"

    basic_auth {
      username = "MY_USERNAME"
      password = "foo"
    }
  }
}
```

### Logs

```text
main.d89b6748.js:2 TypeError: Cannot read properties of null (reading 'forEach')
    at e (main.d89b6748.js:2:853574)
    at main.d89b6748.js:2:853760
    at Array.forEach (<anonymous>)
    at e (main.d89b6748.js:2:853574)
    at Ir (main.d89b6748.js:2:853841)
    at Ni (main.d89b6748.js:2:878982)
    at To (main.d89b6748.js:2:78252)
    at Tl (main.d89b6748.js:2:135365)
    at Eu (main.d89b6748.js:2:124471)
    at yu (main.d89b6748.js:2:124399)
ps @ main.d89b6748.js:2
n.callback @ main.d89b6748.js:2
Ui @ main.d89b6748.js:2
Sl @ main.d89b6748.js:2
El @ main.d89b6748.js:2
vl @ main.d89b6748.js:2
(anonymous) @ main.d89b6748.js:2
wu @ main.d89b6748.js:2
iu @ main.d89b6748.js:2
w @ main.d89b6748.js:2
R @ main.d89b6748.js:2
main.d89b6748.js:2 Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at e (main.d89b6748.js:2:853574)
    at main.d89b6748.js:2:853760
    at Array.forEach (<anonymous>)
    at e (main.d89b6748.js:2:853574)
    at Ir (main.d89b6748.js:2:853841)
    at Ni (main.d89b6748.js:2:878982)
    at To (main.d89b6748.js:2:78252)
    at Tl (main.d89b6748.js:2:135365)
    at Eu (main.d89b6748.js:2:124471)
    at yu (main.d89b6748.js:2:124399)
```

### PR DESCRIPTION
**Pull request by rfratto**
This commit fixes two issues:

* If the component failed to build and was unhealthy, a nil pointer panic would be generated when requesting debug info.
* An empty slice of discovered CRDs failed to be encoded as JSON in a way expected by the UI.

Fixes #4512.

### CODE REVIEW

File: pkg/river/encoding/riverjson/riverjson.go [hunk 1]
```diff
@@ -87,15 +87,6 @@ func encodeFieldAsStatements(prefix []string, field rivertags.Field, fieldValue
...
 
 		switch {
-		case fieldValue.IsZero():
-			// It shouldn't be possible to have a required block which is unset, but
-			// we'll encode something anyway.
-			return []jsonStatement{jsonBlock{
-				Name: strings.Join(fullName, "."),
-				Type: "block",
-				Body: nil,
-			}}
```
Comment (rfratto) [inline pkg/river/encoding/riverjson/riverjson.go:97]: This block was in the wrong place after the logic for block slices was introduced. It should only run for struct blocks.

**Review by mattdurham — APPROVED** [review]
LGTM

**Comment by flokli** [comment]
Thanks! Does CI push a container image somewhere, so I can test it out in my setup?

**Comment by rfratto** [comment]
@flokli There will be a grafana/agent:main-SHA image pushed for every commit to main (but it may take about an hour to show up)

**Comment by flokli** [comment]
`docker.io/grafana/agent:main-11e0087` it is, and I can confirm it doesn't crash the web interface anymore. Thanks!
