### PR TITLE
loki.source.docker: reduce labels-related resource usage

### LINKED ISSUE #4777: CPU consumption for grafana-agent-flow loki scraping
### What's wrong?

I'm using grafana-agent-flow to fetch logs from docker containers and upload them to loki. Grafana is running on host with just 2 docker containers and generates ~ 10 messages per second, but CPU usage looks to high (especially if you will compare it to promtail). Result for ps aux

```
grafana+ 1642768 82.3  4.2 1563584 83032 ?       Ssl  09:59 135:37 /usr/bin/grafana-agent-flow run --server.http.listen-addr=10.20.1.46:12345 --storage.path=/var/lib/grafana-agent-flow /etc/grafana-agent-flow.river
```

Promtail on host with same containers:
```
root        8871  9.5  0.0 6024040 55496 ?       Ssl  Apr13 16394:29 /usr/bin/promtail -config.file=/etc/promtail/config.yml
```

### Steps to reproduce

Tried same config file on 5 hosts in our system with different containers number - grafana-agent-flow consumes more CPU than promtail instance.

### System information

Linux 5.15.0-56-generic, Ubuntu 22.04.1 LTS

### Software version

v0.35.3

### Configuration

```text
logging {
    level = "warn"
}


// we scrape only containers with promtail=enabled label
discovery.docker "containers" {
    host = "unix:///var/run/docker.sock"
    filter {
        name   = "label"
        values = [ "promtail=enabled" ]
    }
}

discovery.relabel "docker" {
    targets = discovery.docker.containers.targets
}

loki.source.docker "default" {
    host       = "unix:///var/run/docker.sock"
    targets    = discovery.relabel.docker.output

    forward_to = [ loki.process.preprocess.receiver ]
}


loki.process "preprocess" {
    forward_to = [ loki.write.loki.receiver ]

    stage.metrics {
        metric.counter {
            name        = "log_lines_read"
            description = "total number of log lines"
            prefix      = "zm_"

            match_all         = true
            action            = "inc"
            max_idle_duration = "24h"
        }
    }

    stage.drop {
        older_than  = "1h"
        drop_counter_reason = "record is too old"
    }

    stage.drop {
        longer_than = "3KB"
        drop_counter_reason = "size is too big"
    }


    stage.metrics {
        metric.counter {
            name        = "log_lines_processed"
            description = "total number of log lines"
            prefix      = "zm_"

            match_all         = true
            action            = "inc"
            max_idle_duration = "24h"
        }
    }
}

loki.write "loki" {
    endpoint {
        url = "http://10.20.1.100:3100/loki/api/v1/push"
    }
}
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by tpaschalis**
#### PR Description
This PR refactors the usage of labels on the `loki.source.docker` containers to reduce CPU usage by ~84% and memory usage by ~91% (`main` vs `fix`)

Screenshot 2023-08-21 at 16 29 26
Screenshot 2023-08-21 at 16 29 03

#### Which issue(s) this PR fixes
Fixes #4777

#### Notes to the Reviewer
I've verified this by using our pyroscope components and checking the profiles on Grafana Cloud with a config like the following

```
pyroscope.scrape "local" {
  targets    = [
    {"__address__" = "localhost:12346", "service_name"="main"},
    {"__address__" = "localhost:12347", "service_name"="fix"},
  ]
  forward_to = [pyroscope.write.grafanacloud.receiver]

  profiling_config {
    profile.process_cpu {
      enabled = true
    }
  }
}

pyroscope.write "grafanacloud" {
  endpoint {
    url = "<url>"
    basic_auth {
      username = "<user>"
      password = "<pass>"
    }
  }
  external_labels = {
    "env" = "tpaschalis-comparison",
  }
}
```

#### PR Checklist
- [X] CHANGELOG.md updated
- [ ] Documentation added (N/A)
- [ ] Tests updated

### CODE REVIEW

File: component/loki/source/docker/internal/dockertarget/target.go [hunk 1]
```diff
@@ -200,24 +203,8 @@ func (t *Target) process(r io.Reader, logStream string) {
...
-		for _, lbl := range processed {
-			if strings.HasPrefix(lbl.Name, "__") {
-				continue
-			}
-			filtered[model.LabelName(lbl.Name)] = model.LabelValue(lbl.Value)
-		}
-
 		t.handler.Chan() <- loki.Entry{
-			Labels: filtered,
+			Labels: logStreamLset,
```
Comment (thampiotr) [inline component/loki/source/docker/internal/dockertarget/target.go:207]: The only concern I'd have here is that may be we should not give away a shared, mutable copy of this. Could use `maps.Copy()`.

Comment (tpaschalis) [reply component/loki/source/docker/internal/dockertarget/target.go:207]: To be honest, we've had a similar [issue](https://github.com/grafana/agent/pull/3861) in the past, but given the overall [promise](https://github.com/grafana/agent/blob/4b8807a517071556c7fd520d7ddd792fbcd311f7/component/component.go#L36-L45) to treat arguments as immutable we decided to only copy/clone on the downstream components that could change the label set (today, only loki.process and loki.relabel), so I don't think it's necessary to do it here as well. WDYT?

Comment (tpaschalis) [reply component/loki/source/docker/internal/dockertarget/target.go:207]: Also, the idea is that we could further reduce the copying-related resource usage with a copy-on-write model eg. only for actual relabeling rules or processing stages that _do_ change the labels, instead of doing it preemptively on every entry passing through.
https://github.com/grafana/agent/blob/8bcc595ecea6b41a83193065a91be17395bb5b91/component/loki/process/process.go#L139-L144

Comment (thampiotr) [reply component/loki/source/docker/internal/dockertarget/target.go:207]: Fair enough - I'm happy with this approach if that's our deliberate choice :) 

One day maybe we could have an immutable wrapper that would not copy? 🤔 not sure if that would be more efficient than copying in our case and how would the implementation look in Go.
