### PR TITLE
Fix an issue with the static to flow converter for blackbox exporter …

### LINKED ISSUE #5451: Static Mode to Flow Configuration Converter - Blackbox Integration is missing Modules in Conversion Output.
### What's wrong?

When trying to convert a Static Mode Configuration that uses the `blackbox` Exporter, the converted output does not include the `modules` and thus the config does not work as expected.

Uncertain if this is an issue, or its not supported, or due to differences/changes it needs manual intervention

If its not an issue, it should probably be added to the Documentation as a known limitation and outline the steps to be taken. (In my case, i could manually minify the existsing YAML and use that in the `config` argument of the `prometheus.exporter.blackbox` component.

### Steps to reproduce

Create a Static Mode Config with the below configuration.
Try and Convert it to Flow Mode (Bypassing the errors)
Review the output Converted Configuration and verify there are no modules showing.

Manually minify the modules YAML value from the original config and add it to the Flow config, and it now works.

### System information

Linux

### Software version

v0.37.1

### Configuration

```text
server:
  log_level: ${GRAFANA_AGENT_LOG_LEVEL:-info}

integrations:
  agent:
    enabled: true
  blackbox:
    enabled: true
    instance: agent-blackbox-exporter
    blackbox_targets:
      # External Endpoints
      ## - DNS Checks
      - name: Google_DNS_Cloudflare_Main
        address: 1.1.1.1
        module: dns_google_com
      - name: Google_DNS_Cloudflare_Alt
        address: 1.0.0.1
        module: dns_google_com
      - name: Google_DNS_Google_Main
        address: 8.8.8.8
        module: dns_google_com
      - name: Google_DNS_Google_Alt
        address: 8.8.4.4
        module: dns_google_com
      - name: Google_DNS_Quad9_Main
        address: 9.9.9.9
        module: dns_google_com
      - name: Google_DNS_Quad9_Alt
        address: 149.112.112.112
        module: dns_google_com
      - name: Grafana_Com_DNS_Cloudflare_Main
        address: 1.1.1.1
        module: dns_grafana_com
      - name: Grafana_Com_DNS_Cloudflare_Alt
        address: 1.0.0.1
        module: dns_grafana_com
      - name: Grafana_Com_DNS_Google_Main
        address: 8.8.8.8
        module: dns_grafana_com
      - name: Grafana_Com_DNS_Google_Alt
        address: 8.8.4.4
        module: dns_grafana_com
      - name: Grafana_Com_DNS_Quad9_Main
        address: 9.9.9.9
        module: dns_grafana_com
      - name: Grafana_Com_DNS_Quad9_Alt
        address: 149.112.112.112
        module: dns_grafana_com
      ## - HTTPS Checks
      - name: Amazon_HTTP
        address: https://amazon.com/
        module: https_ready
      - name: BBC-UK_HTTP
        address: https://bbc.co.uk/
        module: https_ready
      - name: GrafanaCom_HTTP
        address: https://grafana.com
        module: https_ready
      - name: Google_HTTP
        address: https://google.com
        module: https_ready
      - name: Microsoft_HTTP
        address: https://microsoft.com
        module: https_ready
      ## - ICMP Checks
      - name: Amazon_ICMP
        address: amazon.com
        module: icmp
      - name: BBC-UK_ICMP
        address: bbc.co.uk
        module: icmp
      - name: GrafanaCom_ICMP
        address: grafana.com
        module: icmp
      - name: Google_ICMP
        address: google.com
        module: icmp
      - name: Microsoft_ICMP
        address: microsoft.com
        module: icmp
      ## - TCP Connect Checks
      - name: Amazon_TCP
        address: amazon.com:443
        module: tcp_connect
      - name: BBC-UK_TCP
        address: bbc.co.uk:443
        module: tcp_connect
      - name: GrafanaCom_TCP
        address: grafana.com:443
        module: tcp_connect
      - name: Google_TCP
        address: google.com:443
        module: tcp_connect
      - name: Microsoft_TCP
        address: microsoft.com:443
        module: tcp_connect
      # Internal Endpoints
      ## - DNS Checks
      - name: Grafana_DNS
        address: 127.0.0.11
        module: dns_grafana
      ## - HTTP Checks
      - name: Grafana_HTTP
        address: http://grafana:3000
        module: http_ready
      - name: GrafanaHealth_HTTP
        address: http://grafana:3000/api/health
        module: http_ready
      ## - ICMP Checks
      - name: Agent_ICMP
        address: agent
        module: icmp
      - name: Grafana_ICMP
        address: grafana
        module: icmp
      - name: GrafanaImageRenderer_ICMP
        address: renderer
        module: icmp
      - name: Loki_ICMP
        address: loki
        module: icmp
      ## - TCP Connect Checks
      - name: Grafana_TCP
        address: grafana:3000
        module: tcp_connect
    blackbox_config:
      modules:
        dns_google_com:
          prober: dns
          timeout: 5s
          dns:
            transport_protocol: "udp"
            preferred_ip_protocol: "ip4"
            query_name: "google.com"
            query_type: "A"
            valid_rcodes:
              - NOERROR
        dns_grafana_com:
          prober: dns
          timeout: 5s
          dns:
            transport_protocol: "udp"
            preferred_ip_protocol: "ip4"
            query_name: "grafana.com"
            query_type: "A"
            valid_rcodes:
              - NOERROR
        dns_grafana:
          prober: dns
          timeout: 5s
          dns:
            transport_protocol: "udp"
            preferred_ip_protocol: "ip4"
            query_name: "grafana"
            query_type: "A"
            valid_rcodes:
              - NOERROR
        http_ready:
          prober: http
          timeout: 5s
          http:
            valid_status_codes: [200]
            method: GET
            fail_if_not_ssl: false
            preferred_ip_protocol: ip4
            valid_http_versions: 
              - HTTP/1.1
              - HTTP/2.0
        https_ready:
          prober: http
          timeout: 5s
          http:
            valid_status_codes: [200]
            method: GET
            fail_if_not_ssl: true
            preferred_ip_protocol: ip4
            valid_http_versions: 
              - HTTP/1.1
              - HTTP/2.0
        icmp:
          prober: icmp
          timeout: 5s
          icmp:
            preferred_ip_protocol: ip4
        tcp_connect:
          prober: tcp
          tcp:
            preferred_ip_protocol: ip4
  node_exporter:
    enabled: true
    procfs_path: /rootfs/proc
    rootfs_path: /rootfs
    sysfs_path: /rootfs/sys
    relabel_configs:
      - replacement: host
        target_label: instance

metrics:
  wal_directory: /tmp/grafana-agent-wal
  global:
    external_labels:
      cluster: docker-compose
      source: agent-blackbox
    scrape_interval: 30s
    remote_write:
      - url: http://mimir:8080/api/v1/push
        send_exemplars: true
```

Output Flow Converted Config;

```
prometheus.exporter.blackbox "integrations_blackbox" {
	target "Google_DNS_Cloudflare_Main" {
		address = "1.1.1.1"
		module  = "dns_google_com"
	}

	target "Google_DNS_Cloudflare_Alt" {
		address = "1.0.0.1"
		module  = "dns_google_com"
	}

	target "Google_DNS_Google_Main" {
		address = "8.8.8.8"
		module  = "dns_google_com"
	}

	target "Google_DNS_Google_Alt" {
		address = "8.8.4.4"
		module  = "dns_google_com"
	}

	target "Google_DNS_Quad9_Main" {
		address = "9.9.9.9"
		module  = "dns_google_com"
	}

	target "Google_DNS_Quad9_Alt" {
		address = "149.112.112.112"
		module  = "dns_google_com"
	}

	target "Grafana_Com_DNS_Cloudflare_Main" {
		address = "1.1.1.1"
		module  = "dns_grafana_com"
	}

	target "Grafana_Com_DNS_Cloudflare_Alt" {
		address = "1.0.0.1"
		module  = "dns_grafana_com"
	}

	target "Grafana_Com_DNS_Google_Main" {
		address = "8.8.8.8"
		module  = "dns_grafana_com"
	}

	target "Grafana_Com_DNS_Google_Alt" {
		address = "8.8.4.4"
		module  = "dns_grafana_com"
	}

	target "Grafana_Com_DNS_Quad9_Main" {
		address = "9.9.9.9"
		module  = "dns_grafana_com"
	}

	target "Grafana_Com_DNS_Quad9_Alt" {
		address = "149.112.112.112"
		module  = "dns_grafana_com"
	}

	target "Amazon_HTTP" {
		address = "https://amazon.com/"
		module  = "https_ready"
	}

	target "BBC_UK_HTTP" {
		address = "https://bbc.co.uk/"
		module  = "https_ready"
	}

	target "GrafanaCom_HTTP" {
		address = "https://grafana.com"
		module  = "https_ready"
	}

	target "Google_HTTP" {
		address = "https://google.com"
		module  = "https_ready"
	}

	target "Microsoft_HTTP" {
		address = "https://microsoft.com"
		module  = "https_ready"
	}

	target "Amazon_ICMP" {
		address = "amazon.com"
		module  = "icmp"
	}

	target "BBC_UK_ICMP" {
		address = "bbc.co.uk"
		module  = "icmp"
	}

	target "GrafanaCom_ICMP" {
		address = "grafana.com"
		module  = "icmp"
	}

	target "Google_ICMP" {
		address = "google.com"
		module  = "icmp"
	}

	target "Microsoft_ICMP" {
		address = "microsoft.com"
		module  = "icmp"
	}

	target "Amazon_TCP" {
		address = "amazon.com:443"
		module  = "tcp_connect"
	}

	target "BBC_UK_TCP" {
		address = "bbc.co.uk:443"
		module  = "tcp_connect"
	}

	target "GrafanaCom_TCP" {
		address = "grafana.com:443"
		module  = "tcp_connect"
	}

	target "Google_TCP" {
		address = "google.com:443"
		module  = "tcp_connect"
	}

	target "Microsoft_TCP" {
		address = "microsoft.com:443"
		module  = "tcp_connect"
	}

	target "Grafana_DNS" {
		address = "127.0.0.11"
		module  = "dns_grafana"
	}

	target "Grafana_HTTP" {
		address = "http://grafana:3000"
		module  = "http_ready"
	}

	target "GrafanaHealth_HTTP" {
		address = "http://grafana:3000/api/health"
		module  = "http_ready"
	}

	target "Agent_ICMP" {
		address = "agent"
		module  = "icmp"
	}

	target "Grafana_ICMP" {
		address = "grafana"
		module  = "icmp"
	}

	target "GrafanaImageRenderer_ICMP" {
		address = "renderer"
		module  = "icmp"
	}

	target "Loki_ICMP" {
		address = "loki"
		module  = "icmp"
	}

	target "Grafana_TCP" {
		address = "grafana:3000"
		module  = "tcp_connect"
	}
	probe_timeout_offset = "0s"
}

prometheus.scrape "integrations_blackbox" {
	targets         = prometheus.exporter.blackbox.integrations_blackbox.targets
	forward_to      = [prometheus.remote_write.integrations.receiver]
	job_name        = "integrations/blackbox"
	scrape_interval = "30s"
}

prometheus.remote_write "integrations" {
	external_labels = {
		cluster = "docker-compose",
		source  = "agent-blackbox",
	}

	endpoint {
		url = "http://mimir:8080/api/v1/push"

		queue_config { }

		metadata_config { }
	}
}

prometheus.exporter.unix "default" {
	procfs_path = "/rootfs/proc"
	sysfs_path  = "/rootfs/sys"
	rootfs_path = "/rootfs"
}

discovery.relabel "integrations_node_exporter" {
	targets = prometheus.exporter.unix.default.targets

	rule {
		target_label = "instance"
		replacement  = "host"
	}
}

prometheus.scrape "integrations_node_exporter" {
	targets         = discovery.relabel.integrations_node_exporter.output
	forward_to      = [prometheus.remote_write.integrations.receiver]
	job_name        = "integrations/node_exporter"
	scrape_interval = "30s"
}
```

### Logs

```text
AGENT_MODE=flow /home/srt/Downloads/grafana-agent-linux-amd64 convert -f static /home/srt/dev/docker-compose/common/grafana-agent/agent_blackbox.yaml -o /home/srt/dev/docker-compose/common/grafana-agent/converted/agent_blackbox.river
Error: (Info) Converted scrape_configs job_name "integrations/blackbox" into...
        A prometheus.scrape.integrations_blackbox component
(Info) Converted 1 remote_write[s] "" into...
        A prometheus.remote_write.integrations component
(Info) Converted scrape_configs job_name "integrations/node_exporter" into...
        A prometheus.scrape.integrations_node_exporter component
        A discovery.relabel.integrations_node_exporter component
(Warning) Please review your agent command line flags and ensure they are set in your Flow mode config file where necessary.
(Error) unsupported wal_directory metrics config was provided. use the run command flag --storage.path for Flow mode instead.
(Error) unsupported integration agent was provided.
```

### PR DESCRIPTION
**Pull request by erikbaranowski**
…modules

  config not being included in the river output.

#### Which issue(s) this PR fixes

Fixes #5451

#### PR Checklist

- [x] CHANGELOG.md updated
- [ ] Documentation added
- [x] Tests updated
- [x] Config converters updated

### CODE REVIEW

File: component/prometheus/exporter/blackbox/blackbox_test.go [hunk 1]
```diff
@@ -67,6 +72,40 @@ func TestUnmarshalRiverWithInlineConfig(t *testing.T) {
 	require.Contains(t, "http://grafana.com", args.Targets[1].Target)
 	require.Contains(t, "http_2xx", args.Targets[1].Module)
 }
+
+func TestUnmarshalRiverWithInlineConfigYaml(t *testing.T) {
+	riverCfg := `
+		config = "modules:\n  http_2xx:\n    prober: http\n    timeout: 5s\n"
```
Comment (erikbaranowski) [inline component/prometheus/exporter/blackbox/blackbox_test.go:78]: I decided to include this similar test since it validates and demonstrates the traditional yaml format in use for this argument.

File: pkg/integrations/blackbox_exporter/blackbox_exporter.go [hunk 2]
```diff
@@ -39,18 +41,24 @@ type BlackboxTarget struct {
 
 // Config configures the Blackbox integration.
 type Config struct {
-	BlackboxConfigFile string                 `yaml:"config_file,omitempty"`
-	BlackboxTargets    []BlackboxTarget       `yaml:"blackbox_targets"`
-	BlackboxConfig     blackbox_config.Config `yaml:"blackbox_config,omitempty"`
-	ProbeTimeoutOffset float64                `yaml:"probe_timeout_offset,omitempty"`
+	BlackboxConfigFile string           `yaml:"config_file,omitempty"`
+	BlackboxTargets    []BlackboxTarget `yaml:"blackbox_targets"`
+	BlackboxConfig     util.RawYAML     `yaml:"blackbox_config,omitempty"`
```
Comment (rfratto) [inline pkg/integrations/blackbox_exporter/blackbox_exporter.go:46]: As an aside:

This would normally be the kind of thing which would be a breaking change to the code API. To me, that's re-enforcing the idea of putting everything in internal/ for 1.0 until we're ready to pick a subset of packages to expose.

**Review by rfratto — APPROVED** [review]
LGTM!
