### PR TITLE
simplified metrics fix

### LINKED ISSUE #2030: Flow: metrics.mutate applies the mutation on the same input flow metric
metrics.mutate applies the relabel change to the input label which violates the immutability of flowmetric. Since multiple mutates can be working on the same label set this can cause undefined behavior if they are all mutating the same labelset onto itself.

### PR DESCRIPTION
**Pull request by mattdurham**
#### PR Description

Fixes the issue in the mutate function where it is assigning what should be an immutable label set. This is a tighter PR with a low amount of changes to fix the mutate issue and help guard against bad uses of labels.

#### Which issue(s) this PR fixes

Closes #2030

- [X] Tests updated

### CODE REVIEW

File: component/metrics/receiver.go [hunk 1]
```diff
@@ -13,9 +14,51 @@ type Receiver struct {
...
+
+// Relabel applies normal prometheus relabel rules and returns a flow metric. NOTE this may return itself.
+func (fw *FlowMetric) Relabel(cfgs ...*promrelabel.Config) *FlowMetric {
+	retLbls := promrelabel.Process(fw.labels)
+	if retLbls == nil {
+		return nil
+	}
+	if retLbls.Hash() == fw.labels.Hash() {
+		return fw
+	}
```
Comment (rfratto) [inline component/metrics/receiver.go:62]: There's a really minuscule chance of a hash collision here, I'd also make sure that if the hashes match the labels are also identical.

**Review by rfratto — COMMENTED** [review]
I'll give this a closer look tomorrow, but it seems solid

File: component/metrics/receiver.go (hunk 1 above)
Comment (mattdurham) [reply component/metrics/receiver.go:62]: Also entirely forgot to use cfgs...

Comment (mattdurham) [reply component/metrics/receiver.go]: Fixed and added tests.

File: component/common/appendable/appendable.go [hunk 2]
```diff
@@ -79,11 +79,7 @@ func (app *flowAppender) Append(ref storage.SeriesRef, l labels.Labels, t int64,
 	} else {
 		metrics.GlobalRefMapping.RemoveStaleMarker(uint64(ref))
 	}
-	app.buffer[t] = append(app.buffer[t], &metrics.FlowMetric{
-		GlobalRefID: uint64(ref),
-		Labels:      l,
-		Value:       v,
-	})
+	app.buffer[t] = append(app.buffer[t], metrics.NewFlowMetric(uint64(ref), l, v))
```
Comment (rfratto) [inline component/common/appendable/appendable.go:82]: Thinking aloud: 

One of the nice things about the storage.Appendable API is that it runs on the stack: you don't have to allocate a new pointer for each sample when you send it to the WAL. 

Since the buffer is a slice and will exist in the heap anyway, there might be some nice improvements in allocations by making it store a non-pointer value so there's only one big thing to clean up instead of many small pointers.

Our profiles aren't showing that this is a problem right now, so it's not something I'd spend time on immediately, and it's also probably not worth working on while the API is still being shaped out.

File: component/metrics/globalrefmap.go [hunk 3]
```diff
@@ -44,7 +44,7 @@ func newGlobalRefMap() *GlobalRefMap {
 }
 
 // GetOrAddLink is called by a remote_write endpoint component to add mapping and get back the global id.
-func (g *GlobalRefMap) GetOrAddLink(componentID string, localRefID uint64, l labels.Labels) uint64 {
```
Comment (rfratto) [inline component/metrics/globalrefmap.go:47]: Note for later: 

GlobalRefMap is going to be the cause of a lot of bottlenecking because of how much locking it does. The biggest problem is how this is using a Lock and not a RWLock, but even if that weren't true, there's still many concurrent write operations that will be bottlenecked by the other one. 

I would suggest to start thinking about how to make the cache and global IDs as lock free as possible.

File: component/metrics/mutate/mutate.go [hunk 4]
```diff
@@ -101,19 +101,22 @@ func (c *Component) Update(args component.Arguments) error {
 // series. This is a blocker for releasing a production-grade  of the metrics.mutate
 // component.
 func (c *Component) Receive(ts int64, metricArr []*metrics.FlowMetric) {
-	app := c.appendable.Appender(context.Background())
+	c.mut.RLock()
+	defer c.mut.RUnlock()
+
+	relabelledMetrics := make([]*metrics.FlowMetric, 0)
```
Comment (rfratto) [inline component/metrics/mutate/mutate.go:107]: Performance nit: this should have an initial capacity of `len(metricArr)` so that Go doesn't overallocate when appending metrics for small scrape jobs.

File: component/metrics/mutate/mutate.go [hunk 5]
```diff
@@ -101,19 +101,22 @@ func (c *Component) Update(args component.Arguments) error {
 // series. This is a blocker for releasing a production-grade  of the metrics.mutate
 // component.
 func (c *Component) Receive(ts int64, metricArr []*metrics.FlowMetric) {
```
Comment (rfratto) [inline component/metrics/mutate/mutate.go:103]: Note for later:

It feels suspicious that this is an operation that never fails.

File: component/metrics/receiver.go [hunk 6]
```diff
@@ -13,9 +14,51 @@ type Receiver struct {
...
+// GlobalRefID Retrieves the GlobalRefID
+func (fw *FlowMetric) GlobalRefID() uint64 { return fw.globalRefID }
+
+// Value returns the value
+func (fw *FlowMetric) Value() float64 { return fw.value }
+
+// LabelsCopy returns a copy of the labels structure
+func (fw *FlowMetric) LabelsCopy() labels.Labels {
+	return fw.labels.Copy()
+}
```
Comment (rfratto) [inline component/metrics/receiver.go:46]: API nit: There's no reason to have a method for this, the caller can call `fw.RawLabels().Copy()` if they want to make a copy.

File: component/metrics/remotewrite/remote_write.go [hunk 7]
```diff
@@ -173,16 +173,13 @@ func (c *Component) Update(newConfig component.Arguments) error {
...
+		// Currently it doesn't look like the storage interfaces mutate the labels, but thats not a strong
+		// promise. So this should be treated with care.
+		newLocal, err := app.Append(storage.SeriesRef(localID), m.RawLabels(), ts, m.Value())
 		// Add link if there wasn't one before, and we received a valid local id
 		if localID == 0 && newLocal != 0 {
-			metrics.GlobalRefMapping.GetOrAddLink(c.opts.ID, uint64(newLocal), m.Labels)
+			metrics.GlobalRefMapping.GetOrAddLink(c.opts.ID, uint64(newLocal), m)
 		}
 		if err != nil {
 			_ = app.Rollback()
```
Comment (rfratto) [inline component/metrics/remotewrite/remote_write.go:185]: Nit on the log line below (which GitHub won't let me comment on):

Receiving metrics didn't fail, but appending metrics to the WAL did.

**Review by rfratto — APPROVED** [review]

File: component/metrics/globalrefmap.go (hunk 3 above)
Comment (mattdurham) [reply component/metrics/globalrefmap.go:47]: I was going to hold off on making significant changes to the global ref mapping until it either a. becomes a problem or b. we do submodules. Whatever we decide to do with submodules the global ref mapping will probably have to change a fair amount (not to mention other code).

Comment (rfratto) [reply component/metrics/globalrefmap.go:47]: It doesn't have to be changed right now, but I just wanted to point it out as a concern because it introduces much more lock contention across multiple scrape jobs than Prometheus Agent or the static Grafana Agent does.

File: component/metrics/mutate/mutate.go (hunk 5 above)
Comment (mattdurham) [reply component/metrics/mutate/mutate.go:103]: It was hard to handle the failure, ie if it branches out N times and X succeed and Y fail what do you do? The decision was built around making it fire and forget, then have the individual components handle their own failures and not push those failures up the tree.

Comment (rfratto) [reply component/metrics/mutate/mutate.go:103]: Prometheus scrapers have logic that mark the scrape as failed if it can't write to the WAL. We're losing that capability here.

File: component/metrics/receiver.go (hunk 6 above)
Comment (mattdurham) [reply component/metrics/receiver.go:46]: I really wanted to bury RawLabels usage as much as possible since it's very easy to forget to add the copy.

File: component/metrics/mutate/mutate.go (hunk 5 above)
Comment (mattdurham) [reply component/metrics/mutate/mutate.go:103]: Created issue #2035 for further discussion.
