### PR TITLE
loki.source.heroku: use an unchecked collector for server metrics

### LINKED ISSUE #3646: `loki.source.heroku` update can break the metrics endpoint
When `loki.source.heroku` is `Update`'d and the update requires restarting the embedded server, the Agent's `/metrics` endpoint can break with `<metric> was collected before with the same name and label values` errors.

Steps to reproduce:

1. Start agent with this config:
```
loki.relabel "test_relabel" {
    forward_to = []
    rule {
        action = "labeldrop"
        regex  = "rubbish"
    }
}

loki.source.heroku "repro" {
    listener {
        address = "localhost"
        port = "8888"
    }
    relabel_rules = loki.relabel.test_relabel.rules
    forward_to = []
}
```

2. Go to `http://localhost:12345/metrics` and observe metrics are as expected.
3. Change the config's relabel rules, e.g. change the regex attribute in `loki.relabel.test_relabel` rule.
4. `curl http://localhost:12345/-/reload`
5. Go to `http://localhost:12345/metrics` and observe an error similar to:
```
An error has occurred while serving metrics:

4 error(s) occurred:
* collected metric "loki_source_heroku_drain_target_tcp_connections_limit" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"http" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "loki_source_heroku_drain_target_tcp_connections_limit" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"grpc" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "loki_source_heroku_drain_target_tcp_connections" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"http" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "loki_source_heroku_drain_target_tcp_connections" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"grpc" > gauge:<value:0 > } was collected before with the same name and label values
```

Could be related to two different servers registering metrics with the same names?

### PR DESCRIPTION
**Pull request by rfratto**
Every time an HTTP server for `loki.source.heroku` is created, it creates a new weaveworks/common server, and registers the same set of metrics to the provided collector.

By default, these are checked metrics, which causes the agent-wide `/metrics` endpoint to stop working with an error:

    An error has occurred while serving metrics:

    4 error(s) occurred:
    * collected metric "loki_source_heroku_drain_target_tcp_connections_limit" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"http" > gauge:<value:0 > } was collected before with the same name and label values
    * collected metric "loki_source_heroku_drain_target_tcp_connections_limit" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"grpc" > gauge:<value:0 > } was collected before with the same name and label values
    * collected metric "loki_source_heroku_drain_target_tcp_connections" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"http" > gauge:<value:0 > } was collected before with the same name and label values
    * collected metric "loki_source_heroku_drain_target_tcp_connections" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"grpc" > gauge:<value:0 > } was collected before with the same name and label values

This commit adds a new utility method to create an unchecked prometheus.Collector implementation, and then creates a new prometheus.Registry to store server metrics any time a new server is created. The prometheus.Registry instance for the server is then passed to the unchecked prometheus.Collector for handling.

Closes #3646.

### CODE REVIEW

**Comment by rfratto** [comment]
@thampiotr I opened this in draft because I'm not sure it's the approach we want to take, but I wanted to demonstrate one way to tackle the problem. I wouldn't mind closing it if we had better ideas.

File: component/loki/source/heroku/internal/herokutarget/metrics.go [hunk 1]
```diff
@@ -7,22 +7,22 @@ package herokutarget
 import "github.com/prometheus/client_golang/prometheus"
 
 type Metrics struct {
-	herokuEntries *prometheus.CounterVec
-	herokuErrors  *prometheus.CounterVec
+	herokuEntries prometheus.Counter
+	herokuErrors  prometheus.Counter
```
Comment (rfratto) [inline component/loki/source/heroku/internal/herokutarget/metrics.go:11]: There's no reason for these to be vectors if they have no labels.

File: pkg/util/unchecked_collector.go [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+// SetCollector replaces the inner collector.
+func (uc *UncheckedCollector) SetCollector(inner prometheus.Collector) {
+	uc.mut.Lock()
+	defer uc.mut.Unlock()
+
+	uc.inner = inner
+}
+
+// Describe implements [prometheus.Collector]. Because UncheckedCollector is
+// unchecked, nothing is written to the provided ch.
```
Comment (thampiotr) [inline pkg/util/unchecked_collector.go:33]:
```suggestion
// Describe implements [prometheus.Collector]. This implementation should be treated as 
// unchecked by prometheus, so as per [prometheus.Collector] docs, we don't write anything
// to the channel.
```

File: pkg/util/unchecked_collector.go [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+func (uc *UncheckedCollector) Describe(ch chan<- *prometheus.Desc) {
```
Comment (thampiotr) [inline pkg/util/unchecked_collector.go:34]:
```suggestion
func (uc *UncheckedCollector) Describe(_ chan<- *prometheus.Desc) {
```

File: component/loki/source/heroku/heroku.go [hunk 4]
```diff
@@ -67,26 +69,30 @@ type Component struct {
...
 
-	mut    sync.RWMutex
-	args   Arguments
-	fanout []loki.LogsReceiver
-	target *ht.HerokuTarget
+	mut           sync.RWMutex
+	args          Arguments
+	fanout        []loki.LogsReceiver
+	target        *ht.HerokuTarget
+	serverMetrics *util.UncheckedCollector
```
Comment (thampiotr) [inline component/loki/source/heroku/heroku.go:76]: Nit: `serverMetrics` technically doesn't require `mut` for locking since it has its own lock, so we can move it up in the declarations list next to `metrics` and other fields.

File: component/loki/source/heroku/heroku.go [hunk 5]
```diff
@@ -145,8 +151,15 @@ func (c *Component) Update(args component.Arguments) error {
 			}
 		}
 
+		// [ht.NewHerokuTarget] registers new metrics every time it is called. To
+		// avoid issues with re-registering metrics with the same name, we create a
+		// new registry for the target every time we create one, and pass it to an
+		// unchecked collector to bypass uniqueness checking.
+		serverMetrics := prometheus.NewRegistry()
```
Comment (thampiotr) [inline component/loki/source/heroku/heroku.go:158]:
```suggestion
		registry := prometheus.NewRegistry()
```

File: component/loki/source/heroku/heroku.go [hunk 6]
```diff
@@ -145,8 +151,15 @@ func (c *Component) Update(args component.Arguments) error {
...
+		c.serverMetrics.SetCollector(serverMetrics)
+
 		entryHandler := loki.NewEntryHandler(c.handler, func() {})
-		t, err := ht.NewHerokuTarget(c.metrics, c.opts.Logger, entryHandler, rcs, newArgs.Convert(), c.opts.Registerer)
+		t, err := ht.NewHerokuTarget(c.metrics, c.opts.Logger, entryHandler, rcs, newArgs.Convert(), serverMetrics)
```
Comment (thampiotr) [inline component/loki/source/heroku/heroku.go:162]:
```suggestion
		t, err := ht.NewHerokuTarget(c.metrics, c.opts.Logger, entryHandler, rcs, newArgs.Convert(), registry)
```

**Review by thampiotr — APPROVED** [review]
LGTM % a couple of comments and suggestions. 
Thanks for enlightening me with this solution :)

File: component/loki/source/heroku/heroku.go (hunk 4 above)
Comment (rfratto) [reply component/loki/source/heroku/heroku.go:76]: Totally agree. This is something I wish we had a linter for :)

File: component/loki/source/heroku/heroku.go [hunk 7]
```diff
@@ -145,8 +151,15 @@ func (c *Component) Update(args component.Arguments) error {
 			}
 		}
 
+		// [ht.NewHerokuTarget] registers new metrics every time it is called. To
+		// avoid issues with re-registering metrics with the same name, we create a
+		// new registry for the target every time we create one, and pass it to an
+		// unchecked collector to bypass uniqueness checking.
+		registry := prometheus.NewRegistry()
+		c.serverMetrics.SetCollector(serverMetrics)
```
Comment (thampiotr) [inline component/loki/source/heroku/heroku.go:159]:
```suggestion
		c.serverMetrics.SetCollector(registry)
```
I've missed this in suggestions 😅

**Comment by rfratto** [comment]
@thampiotr I found the same issue in loki.source.gcplog (but nowhere else). Going to do the same change there.

**Review by thampiotr — APPROVED** [review]
