### PR TITLE
loki.source.api: fix a bug where incoming structured metadata and parsed are ignored

### LINKED ISSUE #6493: loki.source.api does not forward structured metadata
### What's wrong?

Here's my grafana agent flow config:

```
loki.source.api "loki_proxy" {
        http {
                listen_address = "127.0.0.1"
                listen_port    = 12348
        }
        labels     = {_from = "loki"}
        forward_to = [loki.echo.faro_echo.receiver, loki.write.faro_loki.receiver]
}
```

When I use it (instead of loki's api directly), structured metadata that I pass in through my logs does not reach loki.

For example, the payload is:

```
{
  "streams": [
    {
      "stream": {
        "_from": "loki",
        "app": "certs"
      },
      "values": [
        [
          "1708639858000000000",
          "test payload",
          {
            "level": "log"
          }
        ]
      ]
    }
  ]
}
```

When I push it through agent's proxy, the metadata is not saved; when I do it using loki directly, it works like a charm.

### Steps to reproduce

1. Create a loki.source.api
2. Use it as a proxy to loki, send logs with structured metadata
3. Metadata is not forwarded to loki

### System information

6.1.77-99.164.amzn2023.x86_64

### Software version

Grafana Agent 0.39

### Configuration

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by marchellodev**
#### PR Description

This pull-request fixes a bug in loki.source.api, where incoming structured metadata and parsed fields are not passed further.

#### Which issue(s) this PR fixes

Fixes #6493

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Tests updated

### CODE REVIEW

File: component/loki/source/api/internal/lokipush/push_api_server_test.go [hunk 1]
```diff
@@ -98,9 +99,18 @@ regex = "dropme"
...
+	expectedStructuredMetadata := push.LabelsAdapter{
+		{Name: "i", Value: strconv.Itoa(0)},
+		{Name: "anotherMetaData", Value: "val"},
+	}
+
 	// Spot check the first value in the result to make sure relabel rules were applied properly
 	require.Equal(t, expectedLabels, eh.Received()[0].Labels)
 
+	// Spot check the first value in the result to make sure structured metadata was received properly
+	require.Equal(t, expectedStructuredMetadata, eh.Received()[0].StructuredMetadata)
```
Comment (tpaschalis) [inline component/loki/source/api/internal/lokipush/push_api_server_test.go:112]: We don't ever set this on the entry, so this assertion should fail, right?

**Review by tpaschalis — COMMENTED** [review]
Hey @marchellodev , thanks for the PR and apologies for the belated response!

Could you please rebase with main, put the changelog entry on the correct spot and fix the new testcase you've added? We should be good to go after that!

**Review by tpaschalis — APPROVED** [review]
LGTM, thank you @marchellodev and congrats on landing your first contribution to Grafana Agent!

I can merge once the repored linting error is fixed.

**Comment by marchellodev** [comment]
@tpaschalis Should be good now, thanks!
