### PR TITLE
use remote_write and scrape_config validations from Prometheus

### LINKED ISSUE #80: Instance configs missing Prometheus validation checks
The Agent is missing some validation checks that Prometheus has:

- Validations for [scrape_configs](https://github.com/prometheus/prometheus/blob/1c99adb9fdc79446534e55edba35c676d5e89d57/config/config.go#L243)
- Validations for [remote_write](https://github.com/prometheus/prometheus/blob/1c99adb9fdc79446534e55edba35c676d5e89d57/config/config.go#L269)

Check the links to see what Prometheus does.

The instance configs don't do validation checks on unmarshaling like Prometheus does; rather it's broken up into `ApplyDefaults` and `Validate`. However, [`ApplyDefaults`](https://github.com/grafana/agent/blob/ac14fbd26b6c176406ea89a9f5a5132ac0aca875/pkg/prometheus/instance/instance.go#L109)  and [`Validate`](https://github.com/grafana/agent/blob/ac14fbd26b6c176406ea89a9f5a5132ac0aca875/pkg/prometheus/instance/instance.go#L128) aren't being called from the instance config API; this should also be fixed.

### PR DESCRIPTION
**Pull request by rfratto**
Prometheus was doing some validations on the `remote_write` and `scrape_config` sections per config that we weren't doing yet. To make this a little easier, ApplyDefaults and Validate have been merged.

The scraping service PutConfiguration endpoint will now apply the defaults to the config before passing it through to the KV store; invalid configs will be prevented from reaching the KV store and errors will be returned to the client.

When migrating to this change, if any invalid configs exist in the KV store, the Agent will refuse to start them and log an error. The configs in the KV store should be updated to fix the invalid settings before the Agent will be able to run it.

Fixes #80.

### CODE REVIEW

File: pkg/prom/instance/instance.go [hunk 1]
```diff
@@ -138,15 +122,44 @@ func (c *Config) ApplyDefaults(global *config.GlobalConfig) {
...
+			}
+
+			// We have to add the name of the instance to ensure that generated metrics
+			// are unique across multiple agent instances. The remote write queues currently
+			// globally register their metrics so we can't inject labels here.
+			cfg.Name = c.Name + "-" + hash[:6]
+			generatedName = true
+		}
+
+		if _, ok := rwNames[cfg.Name]; ok {
```
Comment (hoenn) [inline pkg/prom/instance/instance.go:156]: tiny nit: `exists` or `found` instead of `ok`. It's perfectly understandable just kind of weird to have `ok` result in an error :man_shrugging:
