### PR TITLE
Fix zero default scrape interval by initializing global config stanza with defaults (fixes #106)

### LINKED ISSUE #106: Divide by zero when scrape_config is not specified
When running the agent with a bare config that includes a `scrape_config` but that omits specifying `scrape_interval`, I see a crash due to the zero scrap interval:

```
panic: runtime error: integer divide by zero

goroutine 291 [running]:
github.com/prometheus/prometheus/scrape.(*Target).offset(0xc000409900, 0x0, 0xeab27cf2a6289c0a, 0x0)
	/home/rob/grafana/agent/vendor/github.com/prometheus/prometheus/scrape/target.go:161 +0x12d
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc000409a40, 0x0, 0x0, 0x0)
	/home/rob/grafana/agent/vendor/github.com/prometheus/prometheus/scrape/scrape.go:914 +0x77
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	/home/rob/grafana/agent/vendor/github.com/prometheus/prometheus/scrape/scrape.go:423 +0x6ef
```

For reference, the config is

```
server:
  http_listen_address: localhost
  http_listen_port: 9898

prometheus:
  wal_directory: ./wal
  configs:
    - name: myconfig
      remote_write:
        - url: https://prometheus-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: xxx
            password: yyy
      scrape_configs:
        - job_name: 'node'
          static_configs:
            - targets: ['localhost:9100']
```

(I'll submit a PR with a tentative fix; thought I'd file this separately anyway for documentation purposes.)

### PR DESCRIPTION
**Pull request by robx**
Couple of small clean-up commits around config parsing, and then a fix for #106.

New here, do let me know if I should be doing anything here differently!

I found the code around `ApplyDefaults` a bit confusing: Pretty sure that second loop that's removed in https://github.com/grafana/agent/commit/15659e6865fafdad0e5061084985dd61cc2f13ae was redundant, but actually there's a third call via `validateInstance` which doesn't make a whole lot of sense to me. At least it doesn't crash anymore now (for me :TM:).

Fixes #106

### CODE REVIEW

File: pkg/prom/agent.go [hunk 1]
```diff
@@ -62,34 +70,25 @@ func (c *Config) ApplyDefaults() error {
...
-		usedNames[cfg.Name] = struct{}{}
+		usedNames[name] = struct{}{}
 	}
-
-	for i := range c.Configs {
-		err := c.Configs[i].ApplyDefaults(&c.Global)
-		if err != nil {
-			return err
-		}
-	}
```
Comment (rfratto) [inline pkg/prom/agent.go:91]: Thanks for taking this out! I'm not sure how this ended up in here twice but you're right - this was redundant.

**Comment by rfratto** [comment]
Fixes #106

**Comment by robx** [comment]
Thanks for explaining!
