### PR TITLE
Windows Service accept commands immediately

### LINKED ISSUE #1128: Windows Service start timeout if WAL takes to long to load
While replaying the WAL the service does not respond to Windows Service commands, which means if it takes over 30s then the service fails to start and is stopped.

The most likely change is to have the service start handling service commands immediately.

### PR DESCRIPTION
**Pull request by mattdurham**
#### PR Description 

This PR starts the command loop for handling windows service messages immediately instead of waiting for the agent to fully load. It still ensures that the config is loaded correctly. There are some possible race conditions but those are if the service is told to shutdown so impact is low. ie if you start the service then immediately send the stop signal, the entrypoint stop command may not be called.

#### Which issue(s) this PR fixes 

Closes #1128 

#### PR Checklist

- [x] CHANGELOG updated 
- [na] Documentation added
- [na] Tests updated

### CODE REVIEW

File: cmd/agent/service_windows.go [hunk 1]
```diff
@@ -74,20 +80,23 @@ loop:
 			case svc.Interrogate:
 				changes <- c.CurrentStatus
 			case svc.Stop, svc.Shutdown:
-				ep.Stop()
```
Comment (rfratto) [inline cmd/agent/service_windows.go:77]: Hmm, doesn't this mean there's no way to stop the service? Finding a way to tie this in cleanly would be a PITA but IMO for now we can give `ep.Start` a context that we can cancel whenever we need it to shut down.

**Review by rfratto — APPROVED** [review]
Sorry, I know I'm supposed to be on vacation but just happened to notice this. LGTM % nit

File: cmd/agent/service_windows.go (hunk 1 above)
Comment (mattdurham) [reply cmd/agent/service_windows.go:77]: When you say service do you mean the Windows service or entrypoint? The windows service will stop when this returns and the entrypoint will normally stop on line 98. Though there is a possible race condition.

Comment (rfratto) [reply cmd/agent/service_windows.go:77]: Oh, I see, right. Yeah, this is probably fine as-is. Never mind :)

**Review by rlankfo — APPROVED** [review]
