### PR TITLE
clustering: fix handling of empty join-addresses flag

### LINKED ISSUE #5449: clustering: fix condition for mutual exclusivity of join-addresses and discover-peers
To populate the JoinPeers field we're using an expression like `strings.Split(fr.clusterJoinAddr, ",")`. In case of an empty string, this will lead to a slice with an empty element (instead of an empty slice as was the original intent).

This breaks the mutually exclusive comparison between JoinPeers and DiscoverPeers.

https://github.com/grafana/agent/blob/a0c55a76a467c957a0ea2419d806aab076f3e5bd/cmd/internal/flowmode/cluster_builder.go#L86-L88

Leading to errors like the following
```
ts=2023-10-12T11:02:01.653094Z level=info "boringcrypto enabled"=false
Error: at most one of join peers and discover peers may be set
```

### PR DESCRIPTION
**Pull request by tpaschalis**
#### PR Description

We recently almost had this bite us when porting the cadvisor integration to a new component. 

`strings.Split` returns the input string itself if the separator is not found; this meant that for an empty flag, `strings.Split("", ",")` returned a 1-element slice with the empty string, and _not_ an empty slice.

#### Which issue(s) this PR fixes
Fixes #5449 

#### Notes to the Reviewer

Nothing to note.

#### PR Checklist

- [X] CHANGELOG.md updated
- [ ] Documentation added (N/A)
- [X] Tests updated

### CODE REVIEW

File: cmd/internal/flowmode/cluster_builder_test.go [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestBuildClusterService(t *testing.T) {
+	opts := clusterOptions{
+		JoinPeers:     []string{"foo", "bar"},
```
Comment (thampiotr) [inline cmd/internal/flowmode/cluster_builder_test.go:11]: Shouldn't we have a test with `JoinPeers` empty string somewhere, or setting a flag to it?

Comment (tpaschalis) [reply cmd/internal/flowmode/cluster_builder_test.go:11]: Yes, pushing it.

Comment (tpaschalis) [reply cmd/internal/flowmode/cluster_builder_test.go:11]: (sorry, didn't post the comment beforehand).

After taking a look we don't have a good place for putting tests related to flag parsing. I'd like to (sooner or later) move ahead with #4973 which would cover this. I'm merging this to move ahead with the patch release.

**Comment by juyongli** [comment]
Hi, I am the one who reported this defect #108849 grafana-agent-flow clustering mode error. Seems you guys have fixed it. Thanks.

**Comment by tpaschalis** [comment]
You're welcome @juyongli! Let us know how clustering works for you and any other feedback you may have!
