### PR TITLE
[dev.frontend-receiver] Add API key support to app o11y receiver

### LINKED ISSUE #1294: [dev.frontend-receiver] add token auth option
Add option to configure an api key for the receiver endpoint. 

If API key is specified in receiver config, it should be provided with `X-api-key` header when calling the receiver. Failing to provide valid api key should result in `401` response

### PR DESCRIPTION
**Pull request by domasx2**
#### PR Description 

Adds api key support to app o11y receiver. `api_key` can be configured for receiver, and if it is, it is required to be provided via `x-api-key` header on the http request.

#### Which issue(s) this PR fixes 
fixes #1294 

#### PR Checklist

- [X] CHANGELOG updated 
- [X] Documentation added
- [X] Tests updated

### CODE REVIEW

File: pkg/integrations/v2/app_o11y_receiver/handler/handler.go [hunk 1]
```diff
@@ -59,6 +59,12 @@ func (ar *AppO11yHandler) HTTPHandler(logger log.Logger) http.Handler {
 			return
 		}
 
+		// check API key if one is provided
+		if len(ar.config.APIKey) > 0 && r.Header.Get("x-api-key") != ar.config.APIKey {
```
Comment (kpelelis) [inline pkg/integrations/v2/app_o11y_receiver/handler/handler.go:63]: When comparing crypto strings, use [ContstantTimeCompare](https://pkg.go.dev/crypto/subtle#ConstantTimeCompare) to avoid [timing attacks](https://en.wikipedia.org/wiki/Timing_attack)

File: pkg/integrations/v2/app_o11y_receiver/handler/handler_test.go [hunk 2]
```diff
@@ -177,3 +177,65 @@ func TestLargePayload(t *testing.T) {
 	handler.ServeHTTP(rr, req)
 	assert.Equal(t, http.StatusRequestEntityTooLarge, rr.Result().StatusCode)
 }
+
+func TestAPIKeyRequiredButNotProvided(t *testing.T) {
```
Comment (kpelelis) [inline pkg/integrations/v2/app_o11y_receiver/handler/handler_test.go:181]: It's always nice to have more tests than the actual code. It helps a lot. KUDOS

File: CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,8 @@ This release has deprecations. Please read [DEPRECATION] entries and consult
 the [upgrade guide](https://github.com/grafana/agent/blob/main/docs/upgrade-guide/_index.md)
 for detailed information.
 
+- [FEATURE] (beta) Add API key support to app o11y receiver integration (@domasx2)
```
Comment (kpelelis) [inline CHANGELOG.md:7]:
```suggestion
- [FEATURE] (beta) Add API key based authentication support to app o11y receiver integration (@domasx2)
```

**Review by kpelelis — CHANGES_REQUESTED** [review]
Really good stuff. I left a comment about a possible vulnerability

File: pkg/integrations/v2/app_o11y_receiver/handler/handler.go (hunk 1 above)
Comment (domasx2) [reply pkg/integrations/v2/app_o11y_receiver/handler/handler.go]: good one, wasn't aware of this! done

**Review by kpelelis — APPROVED** [review]
