### PR TITLE
Module argument block

### LINKED ISSUE #3224: Flow Modules: Move the argument block to be a config block
Currently, argument blocks for [modules are evaluated once at load time](https://github.com/grafana/agent/blob/a8e1d2bc53fa01c34b1501466a49b931ee18e99a/pkg/flow/flow.go#L253-L275) and injected as variables in the vm.Scope.

Ideally, these are config blocks like `logging`, `tracing`, and `export`.

### LINKED ISSUE #3632: Having logging configuration on a sub-component results into a gopanic
Hi,

I found this by accident. If there is a submodule which contains a logging configuration, the agent will raise a go panic

module.river
```
logging {
  level  = "info"
  format = "logfmt"
}
```

config.river

```
module.file "this" {
  filename = "module.river"
}
```

I may aware that it make no sense to have a logging configuration in a submodule, but a go panic should never be happen.

```
jok@CDT-MB-20200178 flow-remote-configuration % ~/Downloads/grafana-agent/build/grafana-agent-flow run init.river 
ts=2023-04-25T15:38:35.12018Z level=info msg="now listening for http traffic" addr=127.0.0.1:12345
ts=2023-04-25T15:38:35.120329Z level=info msg="running usage stats reporter"
ts=2023-04-25T15:38:35.121413Z level=info trace_id=76cd1ec5d91abb34b4172bffe072e7a2 msg="starting complete graph evaluation"
ts=2023-04-25T15:38:35.121425Z level=info trace_id=76cd1ec5d91abb34b4172bffe072e7a2 msg="finished node evaluation" node_id=logging duration=2µs
ts=2023-04-25T15:38:35.122096Z level=info trace_id=76cd1ec5d91abb34b4172bffe072e7a2 msg="finished node evaluation" node_id=module.file.config duration=665.25µs
ts=2023-04-25T15:38:35.122102Z level=info trace_id=76cd1ec5d91abb34b4172bffe072e7a2 msg="finished complete graph evaluation" duration=736.584µs
ts=2023-04-25T15:38:35.122155Z level=info msg="http server closed" addr=127.0.0.1:12345 err="http: Server closed"
ts=2023-04-25T15:38:35.122172Z level=error msg="failed to start reporter" err="context canceled"
ts=2023-04-25T15:38:35.122173Z level=info msg="http server closed" addr=memory err="http: Server closed"
interrupt received
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1029f32d0]

goroutine 1 [running]:
github.com/grafana/agent/pkg/flow/internal/controller.(*LoggingConfigNode).NodeID(0x78?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/config_logging.go:93
github.com/grafana/agent/pkg/flow/internal/dag.(*Graph).Add(0x140010f1ac8, {0x106ffa220?, 0x0})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/dag/dag.go:69 +0x148
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).populateConfigBlockNodes(0x140005fde60, 0x1007cad1c?, {0x140006ba640, 0x1, 0x20?})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:251 +0x61c
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).loadNewGraph(0x140005fde60, 0x1007ca408?, {0x0, 0x0, 0x0}, {0x140006ba640?, 0x140010f1b98?, 0x1007cad1c?})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:202 +0x50
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply(0x140005fde60, 0x14000f2aae0, {0x0?, 0x0, 0x0}, {0x140006ba640, 0x1, 0x1})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:105 +0x150
github.com/grafana/agent/pkg/flow.(*Flow).LoadFile(0x14000f9b790, 0x14000f2ca20, 0x14000eb8880?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/flow.go:279 +0x364
github.com/grafana/agent/component/module.(*ModuleComponent).LoadFlowContent(0x14000f9b860, 0x10699c100?, {0x14000eb8840?, 0x1?})
        /Users/jok/Downloads/grafana-agent/component/module/module.go:77 +0x144
github.com/grafana/agent/component/module/file.(*Component).Update(0x14000db1700, {0x106685600?, 0x140010f23a0?})
        /Users/jok/Downloads/grafana-agent/component/module/file/file.go:147 +0x168
github.com/grafana/agent/component/module/file.New({{0x140008cbbc0, 0x12}, 0x140002fdc20, {0x14000faa080, 0x1d}, 0x14000f2a720, {0x107036b90, 0x14000fac0f0}, {0x106ffa280, 0x14000cb9a40}, ...}, ...)
        /Users/jok/Downloads/grafana-agent/component/module/file/file.go:86 +0x20c
github.com/grafana/agent/component/module/file.init.0.func1({{0x140008cbbc0, 0x12}, 0x140002fdc20, {0x14000faa080, 0x1d}, 0x14000f2a720, {0x107036b90, 0x14000fac0f0}, {0x106ffa280, 0x14000cb9a40}, ...}, ...)
        /Users/jok/Downloads/grafana-agent/component/module/file/file.go:24 +0xf4
github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).evaluate(0x14000d0d200, 0x0?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/component.go:308 +0x474
github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).Evaluate(0x140003e0c80?, 0x14000f2a6e0?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/component.go:246 +0x20
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).evaluate(0x14000e38c60, {0x106ff80c0, 0x140002fdd10}, 0x1047a1bb6?, {0x107032cf0, 0x14000d0d200})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:467 +0x54
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply.func2({0x106ffa1e0, 0x14000d0d200})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:148 +0x4c8
github.com/grafana/agent/pkg/flow/internal/dag.WalkTopological(0x14000cb99e0, {0x140003e10c0, 0x3, 0x2?}, 0x140010f3250)
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/dag/walk.go:110 +0x180
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply(0x14000e38c60, 0x14000f2a6e0, {0x140006ba610?, 0x1, 0x1}, {0x0, 0x0, 0x0})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:131 +0x7b0
github.com/grafana/agent/pkg/flow.(*Flow).LoadFile(0x14000f9ad00, 0x14000f2c480, 0x140010f35f8?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/flow.go:279 +0x364
github.com/grafana/agent/cmd/internal/flowmode.(*flowRun).Run.func3()
        /Users/jok/Downloads/grafana-agent/cmd/internal/flowmode/cmd_run.go:192 +0x120
github.com/grafana/agent/cmd/internal/flowmode.(*flowRun).Run(0x140000e3b20, {0x16f643888, 0xa})
        /Users/jok/Downloads/grafana-agent/cmd/internal/flowmode/cmd_run.go:297 +0x10d0
github.com/grafana/agent/cmd/internal/flowmode.runCommand.func1(0x140005dd800?, {0x140006b94c0?, 0x1?, 0x1?})
        /Users/jok/Downloads/grafana-agent/cmd/internal/flowmode/cmd_run.go:81 +0x38
github.com/spf13/cobra.(*Command).execute(0x140005dd800, {0x140006b9470, 0x1, 0x1})
        /Users/jok/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x140005dcc00)
        /Users/jok/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jok/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/grafana/agent/cmd/internal/flowmode.Run()
        /Users/jok/Downloads/grafana-agent/cmd/internal/flowmode/flowmode.go:31 +0x198
main.main()
        /Users/jok/Downloads/grafana-agent/cmd/grafana-agent-flow/main.go:32 +0x1c
```

### PR DESCRIPTION
**Pull request by erikbaranowski**
#### PR Description

This PR introduces a significant refactor into module arguments.

- module arguments are now a config block similar to logging, tracing and export.
- introduce ConfigNodeMap for tracking and validating
  - move module config node validation to be done by ConfigNodeMap
- refactor and add a significant amount of testing to module.string
- add a couple tests to module.file

#### Which issue(s) this PR fixes

Closes #3224 
Fixes #3632

#### PR Checklist

- [x] CHANGELOG updated
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: pkg/flow/flow.go [hunk 1]
```diff
@@ -210,7 +207,7 @@ func (c *Flow) Run(ctx context.Context) {
 				}
 
 				level.Debug(c.log).Log("msg", "handling component with updated state", "node_id", updated.NodeID())
-				c.loader.EvaluateDependencies(nil, updated)
```
Comment (erikbaranowski) [inline pkg/flow/flow.go:213]: There was a lot of passing around a nil `*vm.Scope` which I removed. If I was missing some context and need to put it back let me know.

File: pkg/flow/internal/controller/config_argument.go [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+func (cn *ArgumentConfigNode) Block() *ast.BlockStmt {
+	cn.mut.RLock()
+	defer cn.mut.RUnlock()
+	return cn.block
+}
+
+// NodeID implements dag.Node and returns the unique ID for the config node.
+func (cn *ArgumentConfigNode) NodeID() string { return cn.nodeID }
+
+func Arguments(s *vm.Scope) *map[string]any {
```
Comment (erikbaranowski) [inline pkg/flow/internal/controller/config_argument.go:95]: If there's a cleaner way to get the argument.LABEL.value off the scope I'm all ears. I don't love this.

File: component/module/string/string_test.go
Comment (erikbaranowski) [inline component/module/string/string_test.go:1]: Significant revisions and additions here to test a bunch of module/config block scenarios

Comment (erikbaranowski) [inline component/module/string/string_test.go:1]: Significant revisions and additions here to test a bunch of module/config block scenarios

File: pkg/flow/internal/controller/component_references.go [hunk 3]
```diff
@@ -42,8 +43,10 @@ func ComponentReferences(parent *vm.Scope, cn dag.Node, g *dag.Graph) ([]Referen
 
 	refs := make([]Reference, 0, len(traversals))
 	for _, t := range traversals {
-		// Determine if a reference refers to something existing.
-		if _, ok := parent.Lookup(t[0].Name); ok {
+
+		// Determine if a reference refers to something in stdlib.
+		scope := &vm.Scope{Variables: stdlib.Identifiers}
```
[the remark this answers is not in the document]
Comment (rfratto) [reply pkg/flow/internal/controller/component_references.go:47]: Can we restore the original comment? 

https://github.com/grafana/agent/blob/71edccf44fc510e8ab39f5d6991d943eb772d1ff/pkg/flow/internal/controller/component_references.go#L38-L46

File: pkg/flow/flow.go [hunk 4]
```diff
@@ -245,38 +242,11 @@ func (c *Flow) Run(ctx context.Context) {
 //
 // The controller will only start running components after Load is called once
 // without any configuration errors.
-func (c *Flow) LoadFile(file *File, args map[string]any) error {
+func (c *Flow) LoadFile(file *File, args *map[string]any) error {
```
Comment (rfratto) [inline pkg/flow/flow.go:245]: Can we update the PR to not use a pointer to a map? Maps are already fat pointers, so a pointer to a map isn't necessary.

File: pkg/flow/internal/controller/component_references.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (erikbaranowski) [reply pkg/flow/internal/controller/component_references.go:47]: will do on the next round of updates

File: pkg/flow/internal/controller/config_argument.go [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+	if s != nil && s.Variables != nil {
+		if args, ok := s.Variables["argument"]; ok {
+			switch args := args.(type) {
+			case map[string]any:
+				return &args
+			}
+		}
+	}
```
Comment (rfratto) [inline pkg/flow/internal/controller/config_argument.go:105]: nit: ditto here with doing early returns to avoid deeply nesting.

File: pkg/flow/internal/controller/config_argument.go [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+	cn.optional = argument.Optional
+
+	args := Arguments(scope)
+	if args != nil {
+		if _, ok := (*args)[cn.label]; !ok {
+			if !argument.Optional {
+				return fmt.Errorf("missing required argument %q to module", cn.label)
+			}
+		}
+	}
```
Comment (rfratto) [inline pkg/flow/internal/controller/config_argument.go:68]: There's a bug here: if argsis nil, you're bypassing the optional check.

**Review by rfratto — COMMENTED** [review]
Mostly looks good, few small comments. The big issue right now is I don't see any code which clears argument values from the previous apply.

File: pkg/flow/internal/controller/config.go [hunk 7]
```diff
@@ -34,3 +37,166 @@ func NewConfigNode(block *ast.BlockStmt, globals ComponentGlobals, isInModule bo
...
+		logging:     nil,
+		tracing:     nil,
+		argumentMap: map[string]*ArgumentConfigNode{},
+		exportMap:   map[string]*ExportConfigNode{},
+	}
+}
+
+// Append will add a config node to the ConfigNodeMap unless it already exists
+// in which case it will return a diag specifying the problem.
+func (nodeMap *ConfigNodeMap) Append(configNode BlockNode) diag.Diagnostics {
```
[the remark this answers is not in the document]
Comment (erikbaranowski) [reply pkg/flow/internal/controller/config.go:64]: I can. It looks like it will panic in current state and confirmed via local testing. I might want to improve this as part of this PR if we go that route.

https://github.com/grafana/agent/blob/main/pkg/flow/internal/dag/dag.go#L66

[the remark this answers is not in the document]
Comment (rfratto) [reply pkg/flow/internal/controller/config.go:64]: You can also do a Get before adding it to avoid changing the Add implementation

File: pkg/flow/internal/controller/component_references.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (erikbaranowski) [reply pkg/flow/internal/controller/component_references.go]: I reverted the comment and line of code to the pre-modules version

File: pkg/flow/internal/controller/loader.go [hunk 8]
```diff
@@ -472,6 +475,11 @@ func (l *Loader) evaluate(logger log.Logger, parent *vm.Scope, bn BlockNode) err
 		// change when a component gets re-evaluated. We also want to cache the arguments and exports in case of an error
 		l.cache.CacheArguments(c.ID(), c.Arguments())
 		l.cache.CacheExports(c.ID(), c.Exports())
+	case *ArgumentConfigNode:
+		componentId := ComponentID{"argument", c.Label(), "value"}
+		if _, ok := l.cache.exports[componentId.String()]; !ok && c.Optional() {
+			l.cache.CacheExports(componentId, c.Default())
+		}
```
[the remark this answers is not in the document]
Comment (erikbaranowski) [reply pkg/flow/internal/controller/loader.go:491]: I resolved a number of things on the latest commit and will work on this feedback and the remaining related feedback on my next commit.

File: pkg/flow/internal/controller/loader.go [hunk 9]
```diff
@@ -95,14 +94,23 @@ func NewLoader(globals ComponentGlobals) *Loader {
...
 
-	newGraph, diags := l.loadNewGraph(parentScope, componentBlocks, configBlocks)
+	if args != nil {
+		for key, value := range *args {
+			l.cache.CacheExports(
+				ComponentID{"argument", key, "value"},
+				value,
+			)
+		}
+	}
```
[the remark this answers is not in the document]
Comment (erikbaranowski) [reply pkg/flow/internal/controller/loader.go]: I think this was covered by `l.cache.SyncIDs(componentIDs)` toward the end of Apply since I was reusing the existing exports cache. With the update to put these in their own cache that may change.

File: pkg/flow/internal/controller/config.go [hunk 10]
```diff
@@ -34,3 +37,127 @@ func NewConfigNode(block *ast.BlockStmt, globals ComponentGlobals, isInModule bo
...
+		}
+
+		if nodeMap.tracing != nil {
+			diags.Add(diag.Diagnostic{
+				Severity: diag.SeverityLevelError,
+				Message:  "tracing block not allowed inside a module",
+				StartPos: ast.StartPos(nodeMap.tracing.Block()).Position(),
+				EndPos:   ast.EndPos(nodeMap.tracing.Block()).Position(),
+			})
+		}
```
Comment (mattdurham) [inline pkg/flow/internal/controller/config.go:123]: Thoughts on adding a return here and allowing us to get rid of the else/indentation?

File: pkg/flow/internal/controller/config_argument.go [hunk 11]
```diff
@@ -0,0 +1,115 @@
...
+func (cn *ArgumentConfigNode) Block() *ast.BlockStmt {
+	cn.mut.RLock()
+	defer cn.mut.RUnlock()
+	return cn.block
+}
+
+// NodeID implements dag.Node and returns the unique ID for the config node.
+func (cn *ArgumentConfigNode) NodeID() string { return cn.nodeID }
+
+func Arguments(s *vm.Scope) map[string]any {
```
Comment (mattdurham) [inline pkg/flow/internal/controller/config_argument.go:99]: Some comments about how this is sanitizing the passed in `s` would be nice.

File: component/module/string/string_test.go [hunk 12]
```diff
@@ -18,96 +18,198 @@ import (
...
+			argumentModuleContent: argumentConfig + tracingConfig,
+			exportModuleContent:   exportStringConfig,
+			expectedErrorContains: "tracing block not allowed inside a module",
+		},
+		{
+			name:                  "Argument not defined in module source",
+			riverContent:          argumentModuleLoaderConfig + exportModuleLoaderConfig,
+			argumentModuleContent: `argument "different_argument" {}`,
+			exportModuleContent:   exportStringConfig,
+			expectedErrorContains: "is not defined in the module",
```
Comment (erikbaranowski) [inline component/module/string/string_test.go:132]: I removed the check on a specific argument name here because this is not deterministic for some reason. The test would flip between username and password in the error message.

File: pkg/flow/internal/controller/component_references.go [hunk 13]
```diff
@@ -42,8 +43,13 @@ func ComponentReferences(parent *vm.Scope, cn dag.Node, g *dag.Graph) ([]Referen
...
 	refs := make([]Reference, 0, len(traversals))
 	for _, t := range traversals {
-		// Determine if a reference refers to something existing.
-		if _, ok := parent.Lookup(t[0].Name); ok {
+		// We use an empty scope to determine if a reference refers to something in
+		// the stdlib, since vm.Scope.Lookup will search the scope tree + the
+		// stdlib.
+		//
+		// Any call to an stdlib function is ignored.
+		emptyScope := &vm.Scope{Variables: stdlib.Identifiers}
```
Comment (rfratto) [inline pkg/flow/internal/controller/component_references.go:51]: This is no longer an empty scope, and the comment explaining how Lookup works is no longer relevant, since we're shadowing the default scope.

File: pkg/flow/internal/controller/config_argument.go [hunk 14]
```diff
@@ -0,0 +1,122 @@
...
+	}
+
+	args := Arguments(scope)
+	if args != nil {
+		if _, found := (args)[cn.label]; found {
+			return nil
+		}
+	}
+
+	return fmt.Errorf("missing required argument %q to module", cn.label)
```
Comment (rfratto) [inline pkg/flow/internal/controller/config_argument.go:72]: I would like for us to find a way to avoid having ArgumentConfigNode to introspect the scope to validate whether required arguments are provided; it feels complex and error prone.

File: pkg/flow/internal/controller/config.go [hunk 15]
```diff
@@ -34,3 +37,128 @@ func NewConfigNode(block *ast.BlockStmt, globals ComponentGlobals, isInModule bo
...
+}
+
+// NewConfigNodeMap will create an initial ConfigNodeMap. Append must be called
+// to populate NewConfigNodeMap.
+func NewConfigNodeMap() *ConfigNodeMap {
+	return &ConfigNodeMap{
+		logging:     nil,
+		tracing:     nil,
+		argumentMap: map[string]*ArgumentConfigNode{},
+		exportMap:   map[string]*ExportConfigNode{},
```
Comment (rfratto) [inline pkg/flow/internal/controller/config.go:58]: I'm still generally against us defining a second way to track nodes in the graph, even if it's temporary; I would like for us to find a way to reuse dag.Graph as the source of truth for everything related to config nodes.

File: pkg/flow/internal/dag/dag.go [hunk 16]
```diff
@@ -77,6 +80,18 @@ func (g *Graph) Add(n Node) {
 // the graph.
 func (g *Graph) GetByID(id string) Node { return g.nodeByID[id] }
 
+// GetByIDPrefix returns a slice of nodes with an ID Prefix.
+func (g *Graph) GetByIDPrefix(idPrefix string) []Node {
```
Comment (erikbaranowski) [inline pkg/flow/internal/dag/dag.go:84]: This is very inefficient and not how I think we should do this but I made a go at it using just the graph for prototyping purposes. Let me know what you think @rfratto now that the rest of the code has moved in the direction you are looking for.

1 alternative is to track the export/argument ids as they are added then pass those in to the config.go funcs instead.

Another alternative is to implement a tree that is optimized for prefix searching, ie. https://github.com/tchap/go-patricia/

File: pkg/flow/internal/controller/config_argument.go (hunk 14 above)
Comment (erikbaranowski) [reply pkg/flow/internal/controller/config_argument.go]: This has been addressed using the new module argument cache after evaluate is called at a higher level.

File: pkg/flow/internal/controller/config.go (hunk 15 above)
Comment (erikbaranowski) [reply pkg/flow/internal/controller/config.go]: ConfigNodeMap is been removed

File: pkg/flow/internal/controller/loader.go [hunk 17]
```diff
@@ -483,8 +476,12 @@ func (l *Loader) evaluate(logger log.Logger, bn BlockNode) error {
...
 		l.cache.CacheExports(c.ID(), c.Exports())
 	case *ArgumentConfigNode:
-		if _, ok := l.cache.moduleArguments[c.Label()]; !ok && c.Optional() {
-			l.cache.CacheModuleArgument(c.Label(), c.Default())
+		if _, found := l.cache.moduleArguments[c.Label()]; !found {
+			if c.Optional() {
+				l.cache.CacheModuleArgument(c.Label(), c.Default())
+			} else {
+				err = fmt.Errorf("missing required argument %q to module", c.Label())
+			}
```
Comment (rfratto) [inline pkg/flow/internal/controller/loader.go:484]: Thanks for prototyping the change with removing the ConfigNodeMap. I definitely missed that we needed to do a search rather than just a get, so I think the ConfigNodeMap is good as it was. 

That said, I do prefer this approach here for checking for required arguments; can we revert this commit but keep this change in before merging?

**Review by rfratto — APPROVED** [review]
LGTM % final comments to resolve

File: CHANGELOG.md [hunk 18]
```diff
@@ -53,6 +53,9 @@ v0.33.1 (2023-05-01)
 - Fix bug where some capsule values (such as Prometheus receivers) could not
   properly be used as an argument to a module. (@rfratto)
 
+- Return an error message rather than go panic when putting a logging config
+  block inside a module. (@erikbaranowski)
```
Comment (rfratto) [inline CHANGELOG.md:57]: (btw, this needs to be moved out of the v0.33.1 section) 

```suggestion
- Fix an issue where defining `logging` or `tracing` blocks inside of a module would generate a panic instead of returning an error. (@erikbaranowski)
```

File: pkg/flow/internal/controller/loader.go (hunk 17 above)
Comment (erikbaranowski) [reply pkg/flow/internal/controller/loader.go:491]: I reverted and reapplied the parts we wanted to keep.

**Comment by rfratto** [comment]
@mattdurham LGTM from my perspective, do you have anything else you want to see done before this is merged?

**Review by mattdurham — APPROVED** [review]
LGTM shipit

**Comment by erikbaranowski** [comment]
@mattdurham @rfratto thanks for the collab on this big 1. can someone press the merge button please, I can't yet!
