### PR TITLE
fix deadlock when one series is added while another is deleted

### LINKED ISSUE #184: Possible deadlock while truncating the WAL and adding a new series at the same time
It is possible for a deadlock to happen when a truncation is running at the same time as a new series being added. 

The WAL gc process works as such:

1. Iterate over each series stripe, obtaining a lock on the shared mutex stripe. 
2. Lookup the hash stripe, obtaining a lock on the shared mutex stripe if it is on a different stripe than is currently locked. 
3. Delete the series and hash.
4. Release the lock on the hash stripe, if obtained. 
5. Release the lock on the series stripe. 

When a new series is added, we check to see if a series with that hash already exists:

1. Obtain a lock on the hash stripe. 
2. Lookup the series stripe, obtaining a lock on the shared mutex stripe if it is on a different stripe than is currently locked. 
3. Return the series if it exists. 
4. Release the lock on the series stripe, if obtained. 
5. Release the lock on the hash stripe. 

Fundamentally, the problem is that the WAL can not have two concurrent goroutines that can both lock the same mutex more than once. It is OK for the gc process to lock two different stripes, but no other goroutine must do the same. 

Prometheus does not have this problem because their series hashmap points to a series rather than a ref ID. To fix the problem in the Agent, the `seriesHashmap` should point to a `memSeries` and each `memSeries` should store their labels. 

Credit to @amckinley for discovering this issue.

### PR DESCRIPTION
**Pull request by rfratto**
This changes the `seriesHashmap` to refer directly to a `memSeries` rather than a tuple of `(refID, labels)`. This is also what Prometheus does, but was changed early in the design of the Agent before the shared interner existed to lower memory usage. 

The problem with having a `seriesHashmap` that indirectly refers to a series is the requirement of holding two separate locks simultaneously. The garbage collection goroutine _also_ needs to hold two separate locks, which can cause a deadlock if these two goroutines run at the same time. Referring directly to the memory series pointer removes the need for holding two locks when looking up a series. 

Closes #184.

### CODE REVIEW

File: pkg/prom/wal/series.go [hunk 1]
```diff
@@ -200,40 +194,25 @@ func (s *stripeSeries) getByID(id uint64) *memSeries {
...
-
-	j := ref & uint64(s.size-1)
-	if j != i {
-		s.locks[j].RLock()
-		defer s.locks[j].RUnlock()
-	}
+	series := s.hashes[i].get(hash, lset)
+	s.locks[i].RUnlock()
 
-	return s.series[j][ref]
```
Comment (rfratto) [inline pkg/prom/wal/series.go:221]: This is the bulk of the bugfix. This removes the need for obtaining a second lock by changing hashes to store a memSeries directly. All the other code is centered around dealing with how memseries now holds the labels rather than the hash.

**Comment by amckinley** [comment]
Anecdotally, I can say that we've been running this patched version in production for about 30hrs and we've seen this deadlock re-occur. Previously, it would repro in less than 3hrs, so I'm pretty optimistic.

**Comment by rfratto** [comment]
> Anecdotally, I can say that we've been running this patched version in production for about 30hrs and we've seen this deadlock re-occur. Previously, it would repro in less than 3hrs, so I'm pretty optimistic.

Any chance you could provide another goroutine dump from `/debug/pprof/goroutine?debug=2`? If you're seeing the deadlock again at the 30 hour mark I'd suspect it's probably another deadlock somewhere else.

**Comment by amckinley** [comment]
Sorry, typo!! That should have read "and we HAVEN'T seen this deadlock re-occur"!

**Comment by rfratto** [comment]
Ah, no worries, glad it hasn't come back up yet!

**Comment by rfratto** [comment]
This is ready for review and doesn't cause any noticeable memory regressions. I did note that memory is slightly spikier, but average memory usage appears to be unchanged.

**Review by hoenn — APPROVED** [review]
