### PR TITLE
Fix issue with config reload when using a log pipeline with a metric stage

### LINKED ISSUE #2754: failed to unregister all metrics from previous promtail. THIS IS A BUG
I want to use metrics pipeline_stages count the number of error rows in the log. Below is my configuration
```yaml
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  name: mysql
  namespace: loki
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: mysql
  relabelings:
  - action: replace
    sourceLabels:
    - __meta_kubernetes_pod_node_name
    targetLabel: __host__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    replacement: mysql
    targetLabel: job
  - action: replace
    sourceLabels:
    - __meta_kubernetes_pod_container_name
    targetLabel: container
  - action: replace
    replacement: mysql
    targetLabel: cluster
  pipelineStages:
  - docker: {}
  - match:
      selector: '{container="mysql"} |~ ".*[ERROR].*"'
      stages: |
        - regex:
            expression: ".*(?P<error>[ERROR]).*"
        - metrics:
            error_log_lines_total:
              type: Counter
              description: The total number of error log lines
              source: error
              action: inc
```
After the loki-logs pod restarts, I get an error
```
$ kubectl -n loki logs -f loki-logs-2snl9 grafana-agent 
ts=2023-01-12T02:03:50.543250808Z caller=server.go:195 level=info msg="server listening on addresses" http=[::]:8080 grpc=127.0.0.1:12346 http_tls_enabled=false grpc_tls_enabled=false
ts=2023-01-12T02:03:50.579742291Z caller=node.go:85 level=info agent=prometheus component=cluster msg="applying config"
ts=2023-01-12T02:03:50.579889027Z caller=remote.go:180 level=info agent=prometheus component=cluster msg="not watching the KV, none set"
ts=2023-01-12T02:03:50.616783411Z caller=kubernetes.go:313 level=info component=logs logs_config=loki/loki component=discovery discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-01-12T02:03:50.973238948Z caller=kubernetes.go:313 level=info component=logs logs_config=loki/loki component=discovery discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-01-12T02:03:50Z level=info caller=traces/traces.go:143 msg="Traces Logger Initialized" component=traces
ts=2023-01-12T02:03:51.151720301Z caller=integrations.go:138 level=warn msg="integrations-next is enabled. integrations-next is subject to change"
ts=2023-01-12T02:03:51.220365818Z caller=reporter.go:107 level=info msg="running usage stats reporter"
ts=2023-01-12T02:03:55.336275999Z caller=entrypoint.go:246 level=info msg="reload of config file requested"
ts=2023-01-12T02:03:55.520499461Z caller=entrypoint.go:161 level=error msg="failed to update loki" err="failed to unregister all metrics from previous promtail. THIS IS A BUG"
ts=2023-01-12T02:03:55.520617191Z caller=entrypoint.go:257 level=error msg="failed to reload config file" err="changes did not apply successfully"
ts=2023-01-12T02:04:00.336698444Z caller=entrypoint.go:246 level=info msg="reload of config file requested"
```
When I delete metrics pipeline_stages, everything is normal. My deployment method is helm
```
helm install --namespace=loki --values values.yaml loki loki-3.8.0.tgz
```
Please help me with this, thanks

### PR DESCRIPTION
**Pull request by ptodev**
#### PR Description

There is a longstanding bug which prevents the agent config from being reloaded when there is a `metrics` stage in a logging pipeline. 

#### Which issue(s) this PR fixes

Fixes #2754

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [x] Tests updated
- [ ] Config converters updated

### CODE REVIEW

File: internal/component/loki/process/process_test.go [hunk 1]
```diff
@@ -486,3 +488,205 @@ func TestDeadlockWithFrequentUpdates(t *testing.T) {
...
+	}
+
+	c.receiver.Chan() <- logEntry
+
+	wantLabelSet := model.LabelSet{
+		"filename": "/var/log/pods/agent/agent/1.log",
+		"foo":      "bar",
+	}
+
+	for i := 0; i < 1; i++ {
```
Comment (thampiotr) [inline internal/component/loki/process/process_test.go:545]: Why a single step for loop?

File: internal/component/loki/process/process_test.go [hunk 2]
```diff
@@ -486,3 +488,205 @@ func TestDeadlockWithFrequentUpdates(t *testing.T) {
...
+# TYPE loki_process_custom_paulin_test counter
+loki_process_custom_paulin_test{filename="/var/log/pods/agent/agent/1.log",foo="bar"} 1
+`
+
+	if err := testutil.GatherAndCompare(reg,
+		strings.NewReader(expectedMetrics)); err != nil {
+		t.Fatalf("mismatch metrics: %v", err)
+	}
+
+	args1 := Arguments{
```
Comment (thampiotr) [inline internal/component/loki/process/process_test.go:567]:
```suggestion
	updatedArgs := Arguments{
```

File: internal/component/loki/process/process_test.go [hunk 3]
```diff
@@ -486,3 +488,205 @@ func TestDeadlockWithFrequentUpdates(t *testing.T) {
...
+
+	// The component was "updated" with the same config.
+	// We expect the metric to stay the same, because the component should be smart enough to
+	// know that the new config is the same as the old one and it should just keep running as it is.
+	// If it resets the metric, this could cause issues with some users who have a sidecar "autoreloader"
+	// which reloads the collector config every X seconds.
+	// Those users wouldn't expect their metrics to be reset every time the config is reloaded.
+	if err := testutil.GatherAndCompare(reg,
+		strings.NewReader(expectedMetrics)); err != nil {
+		t.Fatalf("mismatch metrics: %v", err)
```
Comment (thampiotr) [inline internal/component/loki/process/process_test.go:581]: Nit: require.NoError to keep it uniform?

File: internal/component/loki/process/process_test.go [hunk 4]
```diff
@@ -486,3 +488,205 @@ func TestDeadlockWithFrequentUpdates(t *testing.T) {
...
+
+	// Make sure there are no metrics - there is no metrics stage in the latest config.
+	if err := testutil.GatherAndCompare(reg,
+		strings.NewReader("")); err != nil {
+		t.Fatalf("mismatch metrics: %v", err)
+	}
+
+	c.receiver.Chan() <- logEntry
+
+	for i := 0; i < 1; i++ {
```
Comment (thampiotr) [inline internal/component/loki/process/process_test.go:609]: same question ;)

File: internal/component/loki/process/process_test.go [hunk 5]
```diff
@@ -486,3 +488,205 @@ func TestDeadlockWithFrequentUpdates(t *testing.T) {
...
+		case logEntry := <-ch.Chan():
+			require.True(t, ts.Equal(logEntry.Timestamp))
+			require.Equal(t, logline, logEntry.Line)
+			require.Equal(t, wantLabelSet, logEntry.Labels)
+		case <-time.After(5 * time.Second):
+			require.FailNow(t, "failed waiting for log line")
+		}
+	}
+
+	// Make sure there are no metrics - there is no metrics stage in the latest config.
```
Comment (thampiotr) [inline internal/component/loki/process/process_test.go:620]:
```suggestion
	// Make sure there are still no metrics after sending log entries.
```

File: internal/component/loki/process/process_test.go [hunk 6]
```diff
@@ -486,3 +488,205 @@ func TestDeadlockWithFrequentUpdates(t *testing.T) {
...
+	if err := testutil.GatherAndCompare(reg,
+		strings.NewReader("")); err != nil {
+		t.Fatalf("mismatch metrics: %v", err)
+	}
+
+	// Use a config which has a metric with a different name,
+	// as well as a metric with the same name.
+	// Only the new metric should be visible.
```
Comment (thampiotr) [inline internal/component/loki/process/process_test.go:628]: Is this correct comment? both metrics are visible

File: internal/component/loki/process/process_test.go (hunk 2 above)
Comment (thampiotr) [reply internal/component/loki/process/process_test.go:567]: I see you have a lot of configs to name here... not a fan of the naming and the length of this test, but you can treat this as a nit

File: internal/util/unregisterer.go [hunk 7]
```diff
@@ -18,6 +18,22 @@ func WrapWithUnregisterer(reg prometheus.Registerer) *Unregisterer {
 	}
 }
 
+func isUncheckedCollector(c prometheus.Collector) bool {
+	descChan := make(chan *prometheus.Desc, 10)
+
+	go func() {
```
Comment (thampiotr) [inline internal/util/unregisterer.go:24]: Starting a goroutine here seems a bit dodgy. Can you achieve the same with select and default in a loop?

File: internal/util/unregisterer.go [hunk 8]
```diff
@@ -18,6 +18,22 @@ func WrapWithUnregisterer(reg prometheus.Registerer) *Unregisterer {
 	}
 }
 
+func isUncheckedCollector(c prometheus.Collector) bool {
```
Comment (thampiotr) [inline internal/util/unregisterer.go:21]: Is that the official definition of the unchecked collector? Could you add a comment?

File: static/traces/traces_test.go [hunk 9]
```diff
@@ -225,7 +225,7 @@ configs:
 	err := dec.Decode(&cfg)
 	require.NoError(t, err)
 
-	logBuffer := bytes.Buffer{}
+	logBuffer := util.SyncBuffer{}
```
Comment (thampiotr) [inline static/traces/traces_test.go:228]: Just curious, why this change?

File: docs/sources/flow/reference/components/loki.process.md [hunk 10]
```diff
@@ -717,6 +717,10 @@ The following blocks are supported inside the definition of `stage.metrics`:
 | metric.gauge     | [metric.gauge][]     | Defines a `gauge` metric.     | no       |
 | metric.histogram | [metric.histogram][] | Defines a `histogram` metric. | no       |
 
+{{< admonition type="note" >}}
+If the configuration file for {{< param "PRODUCT_ROOT_NAME" >}} is reloaded, the metrics will be reset.
```
Comment (clayton-cornell) [inline docs/sources/flow/reference/components/loki.process.md:721]:
```suggestion
The metrics will be reset if you reload the {{< param "PRODUCT_ROOT_NAME" >}} configuration file.
```

Switch it around to make it more active.

File: internal/util/unregisterer.go (hunk 8 above)
Comment (ptodev) [reply internal/util/unregisterer.go:37]: I added a comment to clarify this further.

File: internal/util/unregisterer.go (hunk 7 above)
Comment (ptodev) [reply internal/util/unregisterer.go:40]: I cannot think of an alternative way :/ The Prometheus Go client uses the same kind of code with a buffered channel of size 10 and a goroutine. You never know how many descriptions there will be, and `c.Describe(descChan)` won't return until it sent all those descriptions down a channel.

File: internal/component/loki/process/process_test.go (hunk 2 above)
Comment (ptodev) [reply internal/component/loki/process/process_test.go]: I refactored the whole test to make it more readable. I agree that it was too convoluted.

File: internal/component/loki/process/process_test.go (hunk 6 above)
Comment (ptodev) [reply internal/component/loki/process/process_test.go]: I refactored the test and fixed the comments. It looks much cleaner now :)

**Review by thampiotr — APPROVED** [review]

File: internal/util/unregisterer.go (hunk 7 above)
Comment (ptodev) [reply internal/util/unregisterer.go:40]: Yep, it's in the comment above the function, above line 37 in this file.
