### PR TITLE
remote.http: set health after poll on Update

### LINKED ISSUE #4451: remote.http: Component remains in status Unknown unless first background poll
### What's wrong?

Any remote.http component remains in status unknown unless first background poll.

For components which have 24h poll frequency configured, it takes one day to get greeen.

image

### Steps to reproduce

Setup an http.remote components and start the agent

### System information

MacOS 13.4

### Software version

v0.33.3

### Configuration

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by rfratto**
Previously, the health of the component was only set on background polls, which caused the health of the component to be listed as "Unknown" until a background poll occured.

In cases where the polling interval is extremely infrequent, the component appeared to be permanently in state "Unknown."

Closes #4451.

### CODE REVIEW

File: component/remote/http/http.go [hunk 1]
```diff
@@ -160,25 +160,25 @@ func (c *Component) nextPoll() time.Duration {
 // not be held when calling. After polling, the component's health is updated
 // with the success or failure status.
 func (c *Component) poll() {
-	startTime := time.Now()
```
Comment (rfratto) [inline component/remote/http/http.go:163]: I don't think it makes sense for the health time to be set when the poll _started_, rather than when it _finished._ I'm not sure why I did this initially, but I think it makes more sense with the update time being set to when the health was generated.

**Comment by jkroepke** [comment]
Hi, would this PR part of the next 0.35.0?

**Comment by mattdurham** [comment]
Yes,  l am going to cut another rc today
