### PR TITLE
Reduce likelihood of data loss when remote endpoint has an outage

### LINKED ISSUE #400: Data loss in the remote write when the remote endpoint has an outage
We had a relatively short Cortex outage (10m) on the write path, where the server returned 5xx errors and we've noticed missing samples when the agent was catching up once the outage has been resolved.

## Suspected root cause

After some investigation and discussion with @rfratto, it looks like the cause is the aggressive checkpointing done by the agent.

The agent tries to truncate the WAL every `wal_truncate_frequency` period (defaults to 1 minute):
https://github.com/grafana/agent/blob/master/pkg/prom/instance/instance.go#L658

The `Storage.Truncate()` starts a new WAL segment and then creates a new checkpoint if the number of WAL segments is >= 3 (since a segment is created every 1m by default, there will be at least 3 segments every 2 minutes):
https://github.com/grafana/agent/blob/master/pkg/prom/wal/wal.go#L414

The `wal.Checkpoint()` moves older segments to the checkpoint. This means that segments are removed from the `wal/` directory and moved inside the `wal/checkpoint.xxxxx/` directory.

The remote write replays samples only from the WAL segments (not the checkpoint, because [`readSegment()` is called with `tail=false`](https://github.com/prometheus/prometheus/blob/master/tsdb/wal/watcher.go#L564)), so when an outage occurs on the remote endpoint (eg. Cortex) all samples contained in segments which have been moved to the checkpoint will be skipped (not remote written) once the remote endpoint recovers from the outage.

## Reproduced in the local env

I setup a local Cortex cluster and simulated the outage we had in production and I've verified the agent effectively loose data once Cortex gets back online. To easily show it, I've added a log to the Cortex distributor to print the min/max timestamp of samples within each remote write, I've simulated the outage and seen out the agent behaves:
https://gist.github.com/pracucci/b83c192d253e730b2cf59adeb0fc9e50

Once Cortex is back online, the TSDB `wal.Watcher` (which was paused because all remote write shards queues were full due to the outage) continues to relay the WAL and fails once it tries to read from the current segment, which has already been moved to the checkpoint:

```
ts=2021-02-08T22:32:38.768506Z caller=dedupe.go:112 agent=prometheus instance=485e88be7f25c7cd3e3dadfc714dde9b component=remote level=error remote_name=485e88-a3ff21 url=http://distributor:8001/api/prom/push msg="error tailing WAL" err="open /tmp/485e88be7f25c7cd3e3dadfc714dde9b/wal/00000001: no such file or directory"
```

This leads the `wal.Watcher` to replay the WAL again. It replays the checkpoint first (but it skips samples, it only reads series) and then starts replaying segments. The samples which have been moved to the checkpoint are skipped and this leads to the data loss.

### PR DESCRIPTION
**Pull request by rfratto**
#### PR Description 
This PR increases the WAL truncation frequency default to 60 minutes to reduce the likelihood of samples being moved to a checkpoint when remote_writes are failing. 

An extra measure has been added to the truncate loop where a WAL truncate will be skipped if the last remote_write timestamp hasn't changed. This applies after the `min_wal_time` and `max_wal_time` checks so data older than `max_wal_time` should continue to be deleted.

#### Which issue(s) this PR fixes 
Fixes #400 (kind of, it's not perfect, but it's significantly better).

#### PR Checklist

- [x] CHANGELOG updated 
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Review by codesome — APPROVED** [review]

File: pkg/prom/instance/instance.go [hunk 1]
```diff
@@ -44,7 +44,7 @@ var (
 var (
 	DefaultConfig = Config{
 		HostFilter:           false,
-		WALTruncateFrequency: 1 * time.Minute,
+		WALTruncateFrequency: 60 * time.Minute,
```
Comment (pracucci) [inline pkg/prom/instance/instance.go:47]: ## Some thoughts

Switching the frequency from 1m to 60m it means in agent with low/moderate traffic you will have few segments over the last 60m.

Before this change you were creating a segment every 1m, while after this change a new segment is created once the previous one hit 128MB size or after 60m.

The `Storage.Truncate()` creates a checkpoint if there are at least 3 segments and the checkpoint will contain the low 1/3 of segments. Let's consider two opposite scenarios:
- High volume (1 segment / minute): every 60m we create a checkpoint. The checkpoint contains the oldest 20m and the WAL segments contain the newest 40m. The longest outage we can tolerate is 40m.
- Low volume (1 segment / hour): every 60m we create a checkpoint. Since we have 1 segment / hour, the checkpoint contains the oldest 1h and the WAL segments contain the newest 2h. The longest outage we can tolerate is 2h.

@rfratto @codesome is my analysis ☝️  correct? I'm wondering if:
1. the agent should reduce the max segment size or make it configurable
2. we should document the longest outage without data loss is two third of `wal_truncate_frequency`

**Review by pracucci — APPROVED** [review]
Thanks for working on a improvement. I agree it's not a proper fix, but should definitely improve it.

**Comment by rfratto** [comment]
I am going to merge this, even though it only increases remote_write outage tolerance to 39 minutes or 80 minutes, depending on how long it's been since the last checkpoint. A more permanent solution is being discussed [in a design doc](https://docs.google.com/document/d/1DcaHoWZnA-N5UlQ7sJ0IlPKe4ul2nimWlzWaZSxPkNU/edit).
