### PR TITLE
cadvisor config Fixes #1281

### LINKED ISSUE #1281: [Bug]: cadvisor can't initial correctly
I'm trying to use latest v0.22.0 and cadvisor interintegration.

agent is install by deb packages with root user and this is my config:

```yaml
integrations:
  cadvisor:
    enabled: true
    scrape_interval: 15s
    store_container_labels: false
    docker_only: true
    storage_duration: 10m
    docker: "unix:///var/run/docker.sock"
    enabled_metrics:
      - disk
```

But I got this error log: ` ts=2022-01-18T12:48:44.074899092Z caller=manager.go:372 level=error msg="integration has panicked. THIS IS A BUG!" err="runtime error: index out of range [0] with length 0" integration=cadvisor`

try to compile the latest HEAD and add print to show panic trace:
```text
github.com/grafana/agent/pkg/integrations.(*integrationProcess).Run.func1()
        /home/trim21/proj/agent/pkg/integrations/manager.go:373 +0x7b
panic({0x3870bc0, 0xc00163e2a0})
        /home/trim21/.gvm/versions/go1.17.2.linux.amd64/src/runtime/panic.go:1038 +0x215
github.com/google/cadvisor/container/raw.(*rawFactory).CanHandleAndAccept(0xc0028d3720, {0xc0028d3720, 0x2c})
        /home/trim21/go/pkg/mod/github.com/google/cadvisor@v0.43.0/container/raw/factory.go:74 +0x127
github.com/google/cadvisor/container.NewContainerHandler({0xc0028d3720, 0x19}, 0x15, {0x0, 0x0, 0x0}, 0x25)
        /home/trim21/go/pkg/mod/github.com/google/cadvisor@v0.43.0/container/factory.go:249 +0x1c6
github.com/google/cadvisor/manager.(*manager).createContainerLocked(0xc000d4c2c0, {0xc0028d3720, 0x0}, 0x0)
        /home/trim21/go/pkg/mod/github.com/google/cadvisor@v0.43.0/manager/manager.go:919 +0xca
github.com/google/cadvisor/manager.(*manager).createContainer(0xc000d4c2c0, {0xc0028d3720, 0x19}, 0x9c8f50)
        /home/trim21/go/pkg/mod/github.com/google/cadvisor@v0.43.0/manager/manager.go:906 +0xa5
github.com/google/cadvisor/manager.(*manager).detectSubcontainers(0xc000d4c2c0, {0x3e74258, 0x23})
        /home/trim21/go/pkg/mod/github.com/google/cadvisor@v0.43.0/manager/manager.go:1121 +0x235
github.com/google/cadvisor/manager.(*manager).Start(0xc000d4c2c0)
        /home/trim21/go/pkg/mod/github.com/google/cadvisor@v0.43.0/manager/manager.go:305 +0x26c
github.com/grafana/agent/pkg/integrations/cadvisor.(*Integration).Run(0xc0007bd5d0, {0x445f188, 0xc00197d640})
        /home/trim21/proj/agent/pkg/integrations/cadvisor/cadvisor.go:125 +0x3be
github.com/grafana/agent/pkg/integrations.(*CollectorIntegration).Run(0x0, {0x445f188, 0xc00197d640})
        /home/trim21/proj/agent/pkg/integrations/collector_integration.go:104 +0x2d
github.com/grafana/agent/pkg/integrations.(*integrationProcess).Run(0xc000189930)
        /home/trim21/proj/agent/pkg/integrations/manager.go:384 +0x113
created by github.com/grafana/agent/pkg/integrations.(*Manager).ApplyConfig
        /home/trim21/proj/agent/pkg/integrations/manager.go:290 +0x146f
```

### PR DESCRIPTION
**Pull request by rgeyer**
#### PR Description
This adds the expected zero value for `raw_cgroup_prefix_allowlist` as the default for the cadvisor integration configuration.

#### Which issue(s) this PR fixes 
Fixes #1281 

#### PR Checklist

- [ ] CHANGELOG updated 
- N/A Documentation added
- N/A Tests updated

### CODE REVIEW

File: pkg/integrations/cadvisor/common.go [hunk 1]
```diff
@@ -12,6 +12,9 @@ const name = "cadvisor"
 var DefaultConfig Config = Config{
 	// Common cadvisor config defaults
 	StoreContainerLabels: true,
+	AllowlistedContainerLabels: []string{},
+	EnvMetadataAllowlist: []string{},
+	RawCgroupPrefixAllowlist: []string{"",},
```
Comment (rfratto) [inline pkg/integrations/cadvisor/common.go:17]:
```suggestion
	RawCgroupPrefixAllowlist: []string{""},
```

**Review by rfratto — APPROVED** [review]
Is there a way we can add a test for this? Or would that require docker or something to be running?

**Comment by rgeyer** [comment]
> Is there a way we can add a test for this? Or would that require docker or something to be running?

It would fail... Differently, if there was no docker daemon to actually fetch cadvisor metrics from.

In fact, at first I couldn't even reproduce this error, until I used the config provided in the issue. It seems to only get used by cadvisor when the `docker_only` is set.

So.. We could build a test that expects failure, but the message has to do with connecting to docker (whatever that message ends up being), rather than the config initialization error that was initially caught. 🤔

**Comment by rfratto** [comment]
> It would fail... Differently, if there was no docker daemon to actually fetch cadvisor metrics from.

Our CI [runs with access to a Docker daemon now](https://github.com/grafana/agent/blob/0759ad39817f9dfc7e82985b52d0dedbbc742508/.drone/drone.yml#L44-L46), and the only requirement on the testing side is that you add [build tags](https://github.com/grafana/agent/blob/0759ad39817f9dfc7e82985b52d0dedbbc742508/pkg/operator/hierarchy/hierarchy_test.go#L1-L2) so people can opt out of running tests that require it.

Would that help write a test for this?

**Comment by rgeyer** [comment]
> Would that help write a test for this?

No problem! I've got to wrap up another couple priorities, but I'll be happy to implement this ASAP.

File: pkg/integrations/cadvisor/cadvisor.go [hunk 2]
```diff
@@ -91,6 +91,10 @@ type Integration struct {
 func (i *Integration) Run(ctx context.Context) error {
 	// Do gross global configs. This works, so long as there is only one instance of the cAdvisor integration
 	// per host.
+
+	// klog
+	klog.SetLogger(i.c.logger)
```
Comment (rgeyer) [inline pkg/integrations/cadvisor/cadvisor.go:96]: When running in tests, with parallelization, and the `-race` flag, this triggers a race condition that I can't seem to easily workaround. I'm tempted to remove this completely.

File: pkg/integrations/cadvisor/cadvisor_test.go [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+	// 		// value for raw_cgroup_prefix_allowlist should be returned to a zero value string slice.
+	// 		//
+	// 		var err error
+	// 		panicCfgStr := `
+	// docker_only: true
+	// raw_cgroup_prefix_allowlist: []
+	// `
+	// 		assert.Panics(t, func() { err = run_integration(t, panicCfgStr) })
+	// 		assert.NoError(t, err)
+	// 	})
```
Comment (rgeyer) [inline pkg/integrations/cadvisor/cadvisor_test.go:48]: Ideally, I'd be able to perform this test too, which validates that there *is* a panic when the config is wrong. If this were enabled, and began hanging or failing to panic, we'd know that upstream cadvisor changed in some significant way. Specifically, that a raw_cgroup_prefix_allowlist that has one empty string in a slice, is no longer an expected default.

**Review by rgeyer — COMMENTED** [review]
I spent ENTIRELY too long figuring out how best to test this. In the end, I ran into a lot of issues with parallelization, specifically because of assigning the logger from the agent to `klog` which cadvisor uses internally.

File: pkg/integrations/cadvisor/cadvisor_test.go [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+	// 		// expecting the cadvisor collectors to panic. If this suddenly starts hanging, or does not panic, the default
+	// 		// value for raw_cgroup_prefix_allowlist should be returned to a zero value string slice.
+	// 		//
+	// 		var err error
+	// 		panicCfgStr := `
+	// docker_only: true
+	// raw_cgroup_prefix_allowlist: []
+	// `
+	// 		assert.Panics(t, func() { err = runIntegration(t, panicCfgStr) })
+	// 		assert.NoError(t, err)
```
Comment (colega) [inline pkg/integrations/cadvisor/cadvisor_test.go:47]: This check wouldn't make sense since you asserted that `runIntegration` panics so `err =` assignment is never executed.

File: pkg/integrations/cadvisor/cadvisor.go (hunk 2 above)
Comment (mattdurham) [reply pkg/integrations/cadvisor/cadvisor.go:96]: Possible use of `sync.Once`?

Comment (rgeyer) [reply pkg/integrations/cadvisor/cadvisor.go:96]: Yeah, that *might* have helped. Ultimately, it seems to be that cadvisor isn't properly shutting everything down, and waiting for background go routines to finish before returning. So there's still something which writes to the log after my test is "finished", and that races the next test executing and setting the logger.

That said, with some collab w/ @rfratto, there's only a single test, so we're dodging the bullet for now.

File: pkg/integrations/cadvisor/cadvisor_test.go (hunk 4 above)
Comment (rgeyer) [reply pkg/integrations/cadvisor/cadvisor_test.go]: Yep, excellent point. I was struggling to get the tests working at all, and it never actually executed to that point.

Thanks for the heads up!

**Comment by rfratto** [comment]
@rgeyer how much more work do we need here to get this merged?

**Comment by rgeyer** [comment]
> @rgeyer how much more work do we need here to get this merged? Is it ready for another review round?

Right, sorry, this fell off my radar.

I believe this is "done". If someone wants to give it one more round of review that's fine, else I'm ready to merge.

**Review by rfratto — APPROVED** [review]
