### PR TITLE
converters: Default with localhost in static targets when none provided

### LINKED ISSUE #5447: Unable to Convert a Static Mode Logs Config to Flow Mode Automatically
### What's wrong?

I am trying to convert some of my Static Mode configs to Flow Configs, using the `convert` command.

In this instance, I found that one of my Scrape Jobs was missing from the converted configuration.

In the Static Mode Config, I have a Logs Scrape Job of `job_name: integrations/mysql` but this is not included in the output.

I tried commenting out a few lines (like the expression), incase this was an issue, but it still did not generate and I cant see why.

While I can manually convert the config easily, the purpose was to test the convert tool (so I could compare to my manual config to see what differences there was).

### Steps to reproduce

Create a Static Mode Config with the YAML below.
Convert it to Flow Mode with the `convert` option, and also including the `-b` option to bypass the `wal_directory` issue for Metrics
Check output River file to see if the Logs Scrape Job is included.

### System information

Linux

### Software version

v0.37.1

### Configuration

Static Config;

```text
server:
  log_level: ${GRAFANA_AGENT_LOG_LEVEL:-info}

integrations:

metrics:
  wal_directory: /tmp/grafana-agent-wal
  global:
    external_labels:
      cluster: docker-compose
      source: agent
    scrape_interval: 30s
  configs:
  - name: default
    remote_write:
      - url: http://mimir:8080/api/v1/push
        send_exemplars: true
    scrape_configs:

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: integrations/mysql
        static_configs:
          - labels:
              instance: grafana-mysql-db
              job: integrations/mysql
              __path__: /var/log/mysql/error-log.log #/var/log/mysql/*.log
        pipeline_stages:
          - regex:
              expression: '(?P<timestamp>.+) (?P<thread>[\d]+) \[(?P<label>.+?)\]( \[(?P<err_code>.+?)\] \[(?P<subsystem>.+?)\])? (?P<msg>.+)'
          - labels:
              label:
              err_code:
              subsystem:
          - drop:
              expression: "^ *$"
              drop_counter_reason: "drop empty lines"
    clients:
      - url: http://loki:3100/loki/api/v1/push
        external_labels:
          cluster: docker-compose
          source: agent
````

Flow Mode Converted Config Output;

```
prometheus.remote_write "metrics_default" {
	external_labels = {
		cluster = "docker-compose",
		source  = "agent",
	}

	endpoint {
		name = "default-de1a95"
		url  = "http://mimir:8080/api/v1/push"

		queue_config { }

		metadata_config { }
	}
}

loki.write "logs_default" {
	endpoint {
		url = "http://loki:3100/loki/api/v1/push"
	}
	external_labels = {
		cluster = "docker-compose",
		source  = "agent",
	}
}
```

### Logs

```text
AGENT_MODE=flow /home/srt/Downloads/grafana-agent-linux-amd64 convert -f static /home/srt/dev/docker-compose/common/grafana-agent/agent_with_logs_sql.yaml -o /home/srt/dev/docker-compose/common/grafana-agent/converted/agent_with_logs_sql.river
Error: (Info) Converted 1 remote_write[s] "default-de1a95" into...
        A prometheus.remote_write.metrics_default component
(Warning) global positions configuration is not supported - each Flow Mode's loki.source.file component has its own positions file in the component's data directory
(Warning) server.log_level is not supported - Flow mode components may produce different logs
(Warning) Please review your agent command line flags and ensure they are set in your Flow mode config file where necessary.
(Error) unsupported wal_directory metrics config was provided. use the run command flag --storage.path for Flow mode instead.
```

### PR DESCRIPTION
**Pull request by thampiotr**
#### PR Description

Promtail adds some defaults added to static targets configuration at runtime here: https://github.com/grafana/loki/blob/4a564456861c0ab7441b815aa49a7c0f22a05f4c/clients/pkg/promtail/targets/file/filetargetmanager.go#L102

We were not doing this in config converters, which led to incorrect configs, e.g. https://github.com/grafana/agent/issues/5447

#### Which issue(s) this PR fixes

Fixes #5447

#### PR Checklist

- [x] CHANGELOG.md updated
- [ ] Documentation added
- [x] Tests updated
- [x] Config converters updated

### CODE REVIEW

File: converter/internal/promtailconvert/internal/build/service_discovery.go [hunk 1]
```diff
@@ -107,6 +110,14 @@ func toDiscoveryConfig(cfg *scrapeconfig.Config) prom_discover.Configs {
 	}
 
 	if len(cfg.ServiceDiscoveryConfig.StaticConfigs) != 0 {
+		// Add source and default 'localhost' target to match Promtail's behaviour.
+		// See https://github.com/grafana/loki/blob/4a564456861c0ab7441b815aa49a7c0f22a05f4c/clients/pkg/promtail/targets/file/filetargetmanager.go#L102
```
Comment (thampiotr) [inline converter/internal/promtailconvert/internal/build/service_discovery.go:114]: Reflects this behaviour: https://github.com/grafana/loki/blob/4a564456861c0ab7441b815aa49a7c0f22a05f4c/clients/pkg/promtail/targets/file/filetargetmanager.go#L102 

I'm not aware of a better option to do this.

File: converter/internal/staticconvert/testdata/issue_5447.yaml
Comment (erikbaranowski) [inline converter/internal/staticconvert/testdata/issue_5447.yaml:1]: did you mean to include these files? I'm good with adding a test for this scenario to the staticconvert/testdata if you want but maybe in an existing test or named to describe it instead of the issue. wdyt?

Comment (thampiotr) [reply converter/internal/staticconvert/testdata/issue_5447.yaml:1]: We can remove it if we want to reduce number of test cases. I think the existing test case that I've updated in this PR covers the gist of this change.

**Review by erikbaranowski — APPROVED** [review]
LGTM
