### PR TITLE
Fix parsePostgresURL issue

### LINKED ISSUE #1110: panic: unexpected keypair dbname='XXXX' from pq
Can't start freshly installed grafana agent. Got this error while starting the service:

```
panic: unexpected keypair dbname='xxxx' from pq
Nov 18 22:11:48 ip-10-0-x-xx grafana-agent[13306]: goroutine 1 [running]:
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: github.com/grafana/agent/pkg/integrations/postgres_exporter.parsePostgresURL(0xc00070c140, 0x4d, 0x1, 0x1, 0x0)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/pkg/integrations/postgres_exporter/postgres_exporter.go:90 +0x2eb
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: github.com/grafana/agent/pkg/integrations/postgres_exporter.(*Config).InstanceKey(0xc000125520, 0xc000945d88, 0x13, 0x2, 0x2, 0xc000945d88, 0x13)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/pkg/integrations/postgres_exporter/postgres_exporter.go:58 +0x85
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: github.com/grafana/agent/pkg/integrations.(*Manager).ApplyConfig(0xc000950ea0, 0x1, 0xc000dd2fb0, 0x1, 0x1, 0x0, 0xc0005a00a8, 0x1, 0x1, 0x12a05f200, ...)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/pkg/integrations/manager.go:252 +0x1939
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: github.com/grafana/agent/pkg/integrations.NewManager(0x1, 0xc000dd2fb0, 0x1, 0x1, 0x0, 0xc0005a00a8, 0x1, 0x1, 0x12a05f200, 0x3039, ...)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/pkg/integrations/manager.go:182 +0x1f8
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: main.NewEntrypoint(0xc000d73890, 0xc00096a000, 0xc000dd2b10, 0xc000dd3cf0, 0x4419e5, 0xc000076710)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/cmd/agent/entrypoint.go:93 +0x54a
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: main.main()
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/cmd/agent/main.go:66 +0x1d
```

Sample configuration `/etc/grafana-agent.yml`:

```
integrations:
  postgres_exporter:
    data_source_names:
    - "postgresql://linus:42secret@localhost:5432/postgres?sslmode=disable"
    enabled: true
    
    ......
```

Seems there are bugs with the `postgres_exporter.parsePostgresURL()`

tried to reproduce in this golang playground got the same result: https://play.golang.org/p/oEukXPOHXvc

### PR DESCRIPTION
**Pull request by saputradharma**
#### PR Description 
This PR fix issue `postgres_exporter.parsePostgresURL()` that causes the grafana-agent service wont start.

#### Which issue(s) this PR fixes 
Fixes #1110 

#### PR Checklist

- [ ] CHANGELOG updated 
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by rfratto** [comment]
Hi, thanks for fixing this! Could you take a look at #1112 and try to use that as reference? While this fixes the panic, I think there were other problems that weren't caught yet:

* We want to undo the transformations the parse applied (like in #1112)
* We do want to use `SplitN`, but the N should be 2, not 1. Otherwise this fix will panic if a user has a `=` anywhere in their settings.

File: pkg/integrations/postgres_exporter/postgres_exporter_test.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
+package postgres_exporter
```
Comment (rfratto) [inline pkg/integrations/postgres_exporter/postgres_exporter_test.go:1]: You (unfortunately) need to add `//nolint:golint` to the end of this line so the linter doesn't get upset, see the other file for reference

File: pkg/integrations/postgres_exporter/postgres_exporter_test.go [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+	expected := map[string]string{
+		"dbname":   "'postgres'",
+		"host":     "'localhost'",
+		"password": "'42secret'",
+		"port":     "'5432'",
+		"sslmode":  "'disable'",
+		"user":     "'linus'",
+	}
+
+	actual, _ := parsePostgresURL(dsn)
```
Comment (rfratto) [inline pkg/integrations/postgres_exporter/postgres_exporter_test.go:19]:
```suggestion
	actual, err := parsePostgresURL(dsn)
	require.NoError(t, err)
```

File: pkg/integrations/postgres_exporter/postgres_exporter_test.go [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+	if !reflect.DeepEqual(actual, expected) {
+		t.Errorf("parsePortgresURL failed, actual: %v, expected: %v", actual, expected)
+	}
```
Comment (rfratto) [inline pkg/integrations/postgres_exporter/postgres_exporter_test.go:22]:
```suggestion
	require.Equal(t, actual, expected)
```

File: pkg/integrations/postgres_exporter/postgres_exporter_test.go [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+
+func Test_ParsePostgresURL(t *testing.T) {
+	dsn := "postgresql://linus:42secret@localhost:5432/postgres?sslmode=disable"
+	expected := map[string]string{
+		"dbname":   "'postgres'",
+		"host":     "'localhost'",
+		"password": "'42secret'",
+		"port":     "'5432'",
+		"sslmode":  "'disable'",
+		"user":     "'linus'",
```
Comment (rfratto) [inline pkg/integrations/postgres_exporter/postgres_exporter_test.go:16]: We should make sure that the quotes postgres add also get trimmed out since we use these values for deriving an instance label:

```suggestion
		"dbname":   "postgres",
		"host":     "localhost",
		"password": "42secret",
		"port":     "5432",
		"sslmode":  "disable",
		"user":     "linus",
```

File: pkg/integrations/postgres_exporter/postgres_exporter.go [hunk 5]
```diff
@@ -85,7 +85,7 @@ func parsePostgresURL(url string) (map[string]string, error) {
 	res := map[string]string{}
 
 	for _, keypair := range strings.Split(raw, " ") {
-		parts := strings.SplitN(keypair, "=", 1)
+		parts := strings.Split(keypair, "=")
```
Comment (rfratto) [inline pkg/integrations/postgres_exporter/postgres_exporter.go:88]: This needs to be SplitN with 2 otherwise a valid `=` in a field from a user will cause >2 splits and trigger the panic.

```suggestion
		parts := strings.SplitN(keypair, "=", 2)
```

**Review by rfratto — COMMENTED** [review]
Overall LGTM minus the changes I asked for :) Can you add your fix to the CHANGELOG and give yourself credit?

**Comment by saputradharma** [comment]
Thanks for your guide @rfratto. I've updated my PR. By the way, which version should I put about this fix on the CHANGELOG?

**Comment by rfratto** [comment]
> Thanks for your guide @rfratto. I've updated my PR. 

Thank you!

> By the way, which version should I put about this fix on the CHANGELOG?

Feel free to have the entry say whatever you want :) Something along the lines of "fix panic when using postgres_exporter" would be enough IMO. I had added a snippet about it being introduced in v0.21.0, but that's probably not necessary.

**Review by rfratto — APPROVED** [review]
Ah, sorry for the confusion. I moved the entry to under the "unreleased" section since this hasn't been included in a release yet. 

LGTM, thank you for the quick fix!
