### PR TITLE
river/encoding: fix issue where interface capsules were downcasted to empty objects

### LINKED ISSUE #2361: Flow UI: Panic when viewing otelcol.exporter.otlp component
Given the following config file:

```river
otelcol.exporter.otlp "example" {
	client {
		endpoint = "example:4317"
	}
}
```

Perform the following steps:

* Run Grafana Agent Flow 
* Navigate to http://localhost:12345/component/otelcol.exporter.otlp.example

You will see a panic in stdout. 

<details>
<summary>Panic info</summary>
<pre>
2022-10-13 15:27:43.488277 I | http: panic serving 127.0.0.1:52833: reflect: call of reflect.Value.IsZero on zero Value
goroutine 290 [running]:
net/http.(*conn).serve.func1()
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:1850 +0xb0
panic({0x1072a7de0, 0x1400055d878})
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:890 +0x258
reflect.Value.IsZero({0x0?, 0x0?, 0x140005ff7c0?})
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/reflect/value.go:1602 +0x488
github.com/grafana/agent/pkg/river/encoding.(*attributeField).convertAttribute(0x140005ff7c0, {{0x0?, 0x0?, 0x140013c8fd8?}, 0x10?}, {{0x14000b7c610, 0x1, 0x1}, {0x140013c8fd8, 0x1, ...}, ...})
	/Users/robert/dev/grafana/agent/pkg/river/encoding/attribute.go:46 +0xe8
github.com/grafana/agent/pkg/river/encoding.newAttribute(...)
	/Users/robert/dev/grafana/agent/pkg/river/encoding/attribute.go:20
github.com/grafana/agent/pkg/river/encoding.getFieldsForBlock({0x107c44300?, 0x14000fd3000?})
	/Users/robert/dev/grafana/agent/pkg/river/encoding/block.go:97 +0x348
github.com/grafana/agent/pkg/river/encoding.(*blockField).convertBlock(0x140009763f0, {0x107c44300?, 0x14000fd3000?, 0x140013c8d40?}, {{0x1400087f710, 0x1, 0x1}, {0x140013c8d40, 0x1, 0x1}, ...})
	/Users/robert/dev/grafana/agent/pkg/river/encoding/block.go:47 +0x18c
github.com/grafana/agent/pkg/river/encoding.newBlock(...)
	/Users/robert/dev/grafana/agent/pkg/river/encoding/block.go:22
github.com/grafana/agent/pkg/river/encoding.getFieldsForBlock({0x107abc5a0?, 0x14000fd2fc0?})
	/Users/robert/dev/grafana/agent/pkg/river/encoding/block.go:88 +0x214
github.com/grafana/agent/pkg/river/encoding.ConvertRiverBodyToJSON({0x107abc5a0?, 0x14000fd2fc0?})
	/Users/robert/dev/grafana/agent/pkg/river/encoding/encoding.go:25 +0x28
github.com/grafana/agent/pkg/flow.(*Flow).ComponentJSON(0x0?, {0x107e70b80, 0x140013d2f30}, 0x140016701a0)
	/Users/robert/dev/grafana/agent/pkg/flow/flow_http.go:64 +0x168
github.com/grafana/agent/web/api.(*FlowAPI).json(0x14000956530, 0x140013d2d50?)
	/Users/robert/dev/grafana/agent/web/api/api.go:72 +0x50
github.com/grafana/agent/web/api.(*FlowAPI).listComponentHandler.func1({0x107eaae40, 0x1400096f500}, 0x0?)
	/Users/robert/dev/grafana/agent/web/api/api.go:55 +0xe0
net/http.HandlerFunc.ServeHTTP(0x107eb96c0?, {0x107eaae40?, 0x1400096f500?}, 0x106a5dd20?)
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109 +0x38
github.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP({{0x107e88f60?, 0x1400001ca70?}}, {0x107eb96c0?, 0x140003ec1c0?}, 0x14002042600?)
	/Users/robert/dev/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20220928215038-c85342d513a4/util/httputil/compression.go:90 +0x6c
github.com/gorilla/mux.(*Router).ServeHTTP(0x140020409c0, {0x107eb96c0, 0x140003ec1c0}, 0x140013dae00)
	/Users/robert/dev/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x19c
net/http.serverHandler.ServeHTTP({0x14001cfbd70?}, {0x107eb96c0, 0x140003ec1c0}, 0x140013dae00)
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2947 +0x2c4
net/http.(*conn).serve(0x14001f68640, {0x107ebcb48, 0x140016043c0})
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:1991 +0x560
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:3102 +0x444
</pre>
</details>

### PR DESCRIPTION
**Pull request by rfratto**
This change is similar to the fix introduced in #2369, where calling the `Interface()` method on River values forced a type change from an interface-based capsule to an any-type capsule. This caused the UI to crash when displaying an otelcol component (see #2361).

The new `value.FromRaw` method allows constructing a River value from a reflect.Value directly, avoiding the need to convert to interface{}.

As part of this change, a `!reflect.Value.IsZero()` check has been added for safety; this shouldn't happen in most circumstances unless a value.Null is trying to be encoded.

The CHANGELOG wasn't updated because this behavior only occurs when a component exports a capsule type, which was first introduced in the otelcol.* components which have yet to be released.

Fixes #2361.

### CODE REVIEW

File: pkg/river/internal/value/value.go [hunk 1]
```diff
@@ -106,6 +106,12 @@ func Encode(v interface{}) Value {
 	return makeValue(reflect.ValueOf(v))
 }
 
+// FromRaw converts a reflect.Value into a River Value. It is useful to prevent
+// downcasting a interface into an any.
+func FromRaw(v reflect.Value) Value {
+	return makeValue(v)
+}
```
Comment (rfratto) [inline pkg/river/internal/value/value.go:113]: The need to do this is probably the start of a wider discussion around whether interface types should be capsules. It's fairly hard to reason about in the internal code, and there's still some edge cases where a capsule can be downcasted like when providing it to a `vm.Scope`. 

While it might be more work on component developers, it might be better to easier to reason about not doing things this way. 

cc @grafana/databases-agent

Comment (mattdurham) [reply pkg/river/internal/value/value.go:113]: When you say marker interface, do you mean interfaces would need to have the `Capsule interface` on them?

Comment (rfratto) [reply pkg/river/internal/value/value.go:113]: Yeah, I mean to change the rules so that:

1. Go interfaces are deferenced into their underlying type. 
2. Types which implement `river.Capsule` are forced capsule types. 
3. Go types which have no River mapping (like channels) default to capsule types.

The only new rule here is the first one; currently interface types with at least one method are treated as capsules, though it's too easy for that information to be lost.

Comment (rfratto) [reply pkg/river/internal/value/value.go:113]: Either way, I think making these changes should be something we do later, we still need this bug fix for now, especially since #2431 probably makes it happen for even more components.

**Review by mattdurham — APPROVED** [review]
LGTM
